// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::crowd_control_kind_row_type::CrowdControlKindRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CrowdControl {
    pub id: u64,
    pub entity_id: u64,
    pub source: Option<u64>,
    pub kind: CrowdControlKindRow,
    pub remaining_seconds: f32,
    pub total_seconds: f32,
    pub origin_status_instance_id: u64,
}

impl __sdk::InModule for CrowdControl {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CrowdControl`.
///
/// Provides typed access to columns for query building.
pub struct CrowdControlCols {
    pub id: __sdk::__query_builder::Col<CrowdControl, u64>,
    pub entity_id: __sdk::__query_builder::Col<CrowdControl, u64>,
    pub source: __sdk::__query_builder::Col<CrowdControl, Option<u64>>,
    pub kind: __sdk::__query_builder::Col<CrowdControl, CrowdControlKindRow>,
    pub remaining_seconds: __sdk::__query_builder::Col<CrowdControl, f32>,
    pub total_seconds: __sdk::__query_builder::Col<CrowdControl, f32>,
    pub origin_status_instance_id: __sdk::__query_builder::Col<CrowdControl, u64>,
}

impl __sdk::__query_builder::HasCols for CrowdControl {
    type Cols = CrowdControlCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CrowdControlCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            remaining_seconds: __sdk::__query_builder::Col::new(table_name, "remaining_seconds"),
            total_seconds: __sdk::__query_builder::Col::new(table_name, "total_seconds"),
            origin_status_instance_id: __sdk::__query_builder::Col::new(
                table_name,
                "origin_status_instance_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CrowdControl`.
///
/// Provides typed access to indexed columns for query building.
pub struct CrowdControlIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<CrowdControl, u64>,
    pub id: __sdk::__query_builder::IxCol<CrowdControl, u64>,
    pub origin_status_instance_id: __sdk::__query_builder::IxCol<CrowdControl, u64>,
}

impl __sdk::__query_builder::HasIxCols for CrowdControl {
    type IxCols = CrowdControlIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CrowdControlIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            origin_status_instance_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "origin_status_instance_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CrowdControl {}
