// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::crowd_control_kind_row_type::CrowdControlKindRow;
use super::crowd_control_type::CrowdControl;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `crowd_control`.
///
/// Obtain a handle from the [`CrowdControlTableAccess::crowd_control`] method on [`super::RemoteTables`],
/// like `ctx.db.crowd_control()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.crowd_control().on_insert(...)`.
pub struct CrowdControlTableHandle<'ctx> {
    imp: __sdk::TableHandle<CrowdControl>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `crowd_control`.
pub struct CrowdControlTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CrowdControlTableAccessor {
    type Row = CrowdControl;
    type Handle<'db> = CrowdControlTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.crowd_control()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `crowd_control`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CrowdControlTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CrowdControlTableHandle`], which mediates access to the table `crowd_control`.
    fn crowd_control(&self) -> CrowdControlTableHandle<'_>;
}

impl CrowdControlTableAccess for super::RemoteTables {
    fn crowd_control(&self) -> CrowdControlTableHandle<'_> {
        CrowdControlTableHandle {
            imp: self.imp.get_table::<CrowdControl>("crowd_control"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CrowdControlInsertCallbackId(__sdk::CallbackId);
pub struct CrowdControlDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CrowdControlTableHandle<'ctx> {
    type Row = CrowdControl;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CrowdControl> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CrowdControlTableHandle<'ctx> {
    type Row = CrowdControl;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CrowdControl> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CrowdControlInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrowdControlInsertCallbackId {
        CrowdControlInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CrowdControlInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CrowdControlDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrowdControlDeleteCallbackId {
        CrowdControlDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CrowdControlDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CrowdControlTableHandle<'ctx> {
    type InsertCallbackId = CrowdControlInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrowdControlInsertCallbackId {
        CrowdControlInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CrowdControlInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CrowdControlTableHandle<'ctx> {
    type DeleteCallbackId = CrowdControlDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrowdControlDeleteCallbackId {
        CrowdControlDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CrowdControlDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CrowdControlUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CrowdControlTableHandle<'ctx> {
    type UpdateCallbackId = CrowdControlUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CrowdControlUpdateCallbackId {
        CrowdControlUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CrowdControlUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CrowdControlTableHandle<'ctx> {
    type UpdateCallbackId = CrowdControlUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CrowdControlUpdateCallbackId {
        CrowdControlUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CrowdControlUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `crowd_control`,
/// which allows point queries on the field of the same name
/// via the [`CrowdControlIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.crowd_control().id().find(...)`.
pub struct CrowdControlIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CrowdControl, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CrowdControlTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `crowd_control`.
    pub fn id(&self) -> CrowdControlIdUnique<'ctx> {
        CrowdControlIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CrowdControlIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CrowdControl> {
        self.imp.find(col_val)
    }
}

/// Access to the `origin_status_instance_id` unique index on the table `crowd_control`,
/// which allows point queries on the field of the same name
/// via the [`CrowdControlOriginStatusInstanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.crowd_control().origin_status_instance_id().find(...)`.
pub struct CrowdControlOriginStatusInstanceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CrowdControl, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CrowdControlTableHandle<'ctx> {
    /// Get a handle on the `origin_status_instance_id` unique index on the table `crowd_control`.
    pub fn origin_status_instance_id(&self) -> CrowdControlOriginStatusInstanceIdUnique<'ctx> {
        CrowdControlOriginStatusInstanceIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<u64>("origin_status_instance_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CrowdControlOriginStatusInstanceIdUnique<'ctx> {
    /// Find the subscribed row whose `origin_status_instance_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CrowdControl> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CrowdControl>("crowd_control");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<u64>("origin_status_instance_id", |row| {
        &row.origin_status_instance_id
    });
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CrowdControl>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CrowdControl>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CrowdControl`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait crowd_controlQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CrowdControl`.
    fn crowd_control(&self) -> __sdk::__query_builder::Table<CrowdControl>;
}

impl crowd_controlQueryTableAccess for __sdk::QueryTableAccessor {
    fn crowd_control(&self) -> __sdk::__query_builder::Table<CrowdControl> {
        __sdk::__query_builder::Table::new("crowd_control")
    }
}
