// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_instance_row_type::ItemInstanceRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LootBagSlot {
    pub id: u64,
    pub bag_id: u64,
    pub slot_index: u8,
    pub item: ItemInstanceRow,
}

impl __sdk::InModule for LootBagSlot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LootBagSlot`.
///
/// Provides typed access to columns for query building.
pub struct LootBagSlotCols {
    pub id: __sdk::__query_builder::Col<LootBagSlot, u64>,
    pub bag_id: __sdk::__query_builder::Col<LootBagSlot, u64>,
    pub slot_index: __sdk::__query_builder::Col<LootBagSlot, u8>,
    pub item: __sdk::__query_builder::Col<LootBagSlot, ItemInstanceRow>,
}

impl __sdk::__query_builder::HasCols for LootBagSlot {
    type Cols = LootBagSlotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LootBagSlotCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            bag_id: __sdk::__query_builder::Col::new(table_name, "bag_id"),
            slot_index: __sdk::__query_builder::Col::new(table_name, "slot_index"),
            item: __sdk::__query_builder::Col::new(table_name, "item"),
        }
    }
}

/// Indexed column accessor struct for the table `LootBagSlot`.
///
/// Provides typed access to indexed columns for query building.
pub struct LootBagSlotIxCols {
    pub bag_id: __sdk::__query_builder::IxCol<LootBagSlot, u64>,
    pub id: __sdk::__query_builder::IxCol<LootBagSlot, u64>,
}

impl __sdk::__query_builder::HasIxCols for LootBagSlot {
    type IxCols = LootBagSlotIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LootBagSlotIxCols {
            bag_id: __sdk::__query_builder::IxCol::new(table_name, "bag_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LootBagSlot {}
