// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LootTakeAllArgs {
    pub bag_id: u64,
}

impl From<LootTakeAllArgs> for super::Reducer {
    fn from(args: LootTakeAllArgs) -> Self {
        Self::LootTakeAll {
            bag_id: args.bag_id,
        }
    }
}

impl __sdk::InModule for LootTakeAllArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `loot_take_all`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait loot_take_all {
    /// Request that the remote module invoke the reducer `loot_take_all` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`loot_take_all:loot_take_all_then`] to run a callback after the reducer completes.
    fn loot_take_all(&self, bag_id: u64) -> __sdk::Result<()> {
        self.loot_take_all_then(bag_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `loot_take_all` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn loot_take_all_then(
        &self,
        bag_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl loot_take_all for super::RemoteReducers {
    fn loot_take_all_then(
        &self,
        bag_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LootTakeAllArgs { bag_id }, callback)
    }
}
