// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.1 (commit 4d9aa49594d59bf09f949b83c30413e43bf0805a).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ability_selection_row_type;
pub mod account_economy_table;
pub mod account_economy_type;
pub mod account_type;
pub mod active_status_table;
pub mod active_status_type;
pub mod aoe_region_table;
pub mod aoe_region_type;
pub mod aoe_shape_row_type;
pub mod aoe_targeting_row_type;
pub mod api_key_meta_type;
pub mod api_key_type;
pub mod armor_cast_reducer;
pub mod armor_inscription_row_type;
pub mod authenticate_api_key_reducer;
pub mod award_resonance_xp_reducer;
pub mod boss_phase_row_type;
pub mod boss_state_table;
pub mod boss_state_type;
pub mod cancel_buy_order_reducer;
pub mod cancel_sell_order_reducer;
pub mod cast_ended_event_type;
pub mod cast_ended_table;
pub mod cast_kind_row_type;
pub mod cast_source_row_type;
pub mod cast_state_table;
pub mod cast_state_type;
pub mod cast_weapon_reducer;
pub mod character_wallet_table;
pub mod character_wallet_type;
pub mod claim_npc_item_reducer;
pub mod color_row_type;
pub mod combine_item_reducer;
pub mod cooldown_table;
pub mod cooldown_type;
pub mod craft_session_table;
pub mod craft_session_type;
pub mod create_api_key_reducer;
pub mod crowd_control_kind_row_type;
pub mod crowd_control_table;
pub mod crowd_control_type;
pub mod damage_event_row_type;
pub mod damage_event_table;
pub mod delete_character_reducer;
pub mod destroy_item_reducer;

pub mod effect_payload_filter_row_type;
pub mod effect_payload_kind_row_type;
pub mod effect_payload_row_type;
pub mod effect_payload_selection_row_type;
pub mod enemy_ai_table;
pub mod enemy_ai_type;
pub mod entity_kind_row_type;
pub mod entity_state_row_type;
pub mod entity_stats_table;
pub mod entity_stats_type;
pub mod equip_item_reducer;
pub mod equipment_table;
pub mod equipment_table_type;
pub mod game_entity_table;
pub mod game_entity_type;
pub mod gather_session_table;
pub mod gather_session_type;
pub mod gather_yield_event_type;
pub mod gather_yield_table;
pub mod gm_clear_prop_override_reducer;
pub mod gm_grant_gold_reducer;
pub mod gm_reseed_world_reducer;
pub mod gm_set_prop_override_reducer;
pub mod heartbeat_reducer;
pub mod hotbar_row_type;
pub mod hotbar_table;
pub mod hotbar_type;
pub mod inventory_table;
pub mod inventory_table_type;
pub mod item_instance_row_type;
pub mod join_reducer;
pub mod known_ancient_language_table;
pub mod known_ancient_language_table_type;
pub mod leave_reducer;
pub mod login_reducer;
pub mod logout_reducer;
pub mod loot_bag_slot_table;
pub mod loot_bag_slot_type;
pub mod loot_bag_table;
pub mod loot_bag_type;
pub mod loot_source_row_type;
pub mod loot_take_all_reducer;
pub mod loot_take_gold_reducer;
pub mod loot_take_reducer;
pub mod market_buy_order_table;
pub mod market_buy_order_type;
pub mod market_buy_reducer;
pub mod market_sell_order_table;
pub mod market_sell_order_type;
pub mod market_sell_reducer;
pub mod market_table;
pub mod market_type;
pub mod modifier_kind_row_type;
pub mod move_item_reducer;
pub mod move_to_reducer;
pub mod my_api_keys_table;
pub mod npc_table;
pub mod npc_type;
pub mod party_accept_reducer;
pub mod party_decline_reducer;
pub mod party_invite_reducer;
pub mod party_join_reducer;
pub mod party_leave_reducer;
pub mod party_member_row_type;
pub mod party_member_table;
pub mod party_request_kind_type;
pub mod party_request_row_type;
pub mod party_request_table;
pub mod party_row_type;
pub mod party_table;
pub mod periodic_effect_table;
pub mod periodic_effect_type;
pub mod place_buy_order_reducer;
pub mod place_sell_order_reducer;
pub mod player_message_event_type;
pub mod player_message_table;
pub mod player_stats_table;
pub mod player_stats_type;
pub mod player_table;
pub mod player_type;
pub mod projectile_table;
pub mod projectile_type;
pub mod prop_override_table;
pub mod prop_override_type;
pub mod register_reducer;
pub mod release_cast_reducer;
pub mod resonance_table;
pub mod resonance_type;
pub mod resource_node_table;
pub mod resource_node_type;
pub mod respawn_reducer;
pub mod revoke_api_key_reducer;
pub mod role_row_type;
pub mod secondary_word_row_type;
pub mod send_chat_message_reducer;
pub mod session_table;
pub mod session_type;
pub mod set_ability_selection_reducer;
pub mod set_armor_inscription_reducer;

pub mod set_resonance_xp_reducer;
pub mod set_root_inscription_reducer;
pub mod slot_inscription_row_type;
pub mod spell_visual_effect_event_type;
pub mod spell_visual_effect_table;
pub mod split_item_reducer;
pub mod start_craft_reducer;
pub mod start_gather_reducer;
pub mod stat_modifier_table;
pub mod stat_modifier_type;
pub mod stats_row_type;
pub mod stop_craft_reducer;
pub mod stop_gather_reducer;
pub mod stop_reducer;
pub mod threat_table;
pub mod threat_type;
pub mod tick_schedule_type;
pub mod tick_stats_table;
pub mod tick_stats_type;
pub mod unequip_item_reducer;
pub mod vec_3_row_type;
pub mod weapon_inscription_row_type;

pub use ability_selection_row_type::AbilitySelectionRow;
pub use account_economy_table::*;
pub use account_economy_type::AccountEconomy;
pub use account_type::Account;
pub use active_status_table::*;
pub use active_status_type::ActiveStatus;
pub use aoe_region_table::*;
pub use aoe_region_type::AoeRegion;
pub use aoe_shape_row_type::AoeShapeRow;
pub use aoe_targeting_row_type::AoeTargetingRow;
pub use api_key_meta_type::ApiKeyMeta;
pub use api_key_type::ApiKey;
pub use armor_cast_reducer::armor_cast;
pub use armor_inscription_row_type::ArmorInscriptionRow;
pub use authenticate_api_key_reducer::authenticate_api_key;
pub use award_resonance_xp_reducer::award_resonance_xp;
pub use boss_phase_row_type::BossPhaseRow;
pub use boss_state_table::*;
pub use boss_state_type::BossState;
pub use cancel_buy_order_reducer::cancel_buy_order;
pub use cancel_sell_order_reducer::cancel_sell_order;
pub use cast_ended_event_type::CastEndedEvent;
pub use cast_ended_table::*;
pub use cast_kind_row_type::CastKindRow;
pub use cast_source_row_type::CastSourceRow;
pub use cast_state_table::*;
pub use cast_state_type::CastState;
pub use cast_weapon_reducer::cast_weapon;
pub use character_wallet_table::*;
pub use character_wallet_type::CharacterWallet;
pub use claim_npc_item_reducer::claim_npc_item;
pub use color_row_type::ColorRow;
pub use combine_item_reducer::combine_item;
pub use cooldown_table::*;
pub use cooldown_type::Cooldown;
pub use craft_session_table::*;
pub use craft_session_type::CraftSession;
pub use create_api_key_reducer::create_api_key;
pub use crowd_control_kind_row_type::CrowdControlKindRow;
pub use crowd_control_table::*;
pub use crowd_control_type::CrowdControl;
pub use damage_event_row_type::DamageEventRow;
pub use damage_event_table::*;
pub use delete_character_reducer::delete_character;
pub use destroy_item_reducer::destroy_item;

pub use effect_payload_filter_row_type::EffectPayloadFilterRow;
pub use effect_payload_kind_row_type::EffectPayloadKindRow;
pub use effect_payload_row_type::EffectPayloadRow;
pub use effect_payload_selection_row_type::EffectPayloadSelectionRow;
pub use enemy_ai_table::*;
pub use enemy_ai_type::EnemyAi;
pub use entity_kind_row_type::EntityKindRow;
pub use entity_state_row_type::EntityStateRow;
pub use entity_stats_table::*;
pub use entity_stats_type::EntityStats;
pub use equip_item_reducer::equip_item;
pub use equipment_table::*;
pub use equipment_table_type::EquipmentTable;
pub use game_entity_table::*;
pub use game_entity_type::GameEntity;
pub use gather_session_table::*;
pub use gather_session_type::GatherSession;
pub use gather_yield_event_type::GatherYieldEvent;
pub use gather_yield_table::*;
pub use gm_clear_prop_override_reducer::gm_clear_prop_override;
pub use gm_grant_gold_reducer::gm_grant_gold;
pub use gm_reseed_world_reducer::gm_reseed_world;
pub use gm_set_prop_override_reducer::gm_set_prop_override;
pub use heartbeat_reducer::heartbeat;
pub use hotbar_row_type::HotbarRow;
pub use hotbar_table::*;
pub use hotbar_type::Hotbar;
pub use inventory_table::*;
pub use inventory_table_type::InventoryTable;
pub use item_instance_row_type::ItemInstanceRow;
pub use join_reducer::join;
pub use known_ancient_language_table::*;
pub use known_ancient_language_table_type::KnownAncientLanguageTable;
pub use leave_reducer::leave;
pub use login_reducer::login;
pub use logout_reducer::logout;
pub use loot_bag_slot_table::*;
pub use loot_bag_slot_type::LootBagSlot;
pub use loot_bag_table::*;
pub use loot_bag_type::LootBag;
pub use loot_source_row_type::LootSourceRow;
pub use loot_take_all_reducer::loot_take_all;
pub use loot_take_gold_reducer::loot_take_gold;
pub use loot_take_reducer::loot_take;
pub use market_buy_order_table::*;
pub use market_buy_order_type::MarketBuyOrder;
pub use market_buy_reducer::market_buy;
pub use market_sell_order_table::*;
pub use market_sell_order_type::MarketSellOrder;
pub use market_sell_reducer::market_sell;
pub use market_table::*;
pub use market_type::Market;
pub use modifier_kind_row_type::ModifierKindRow;
pub use move_item_reducer::move_item;
pub use move_to_reducer::move_to;
pub use my_api_keys_table::*;
pub use npc_table::*;
pub use npc_type::Npc;
pub use party_accept_reducer::party_accept;
pub use party_decline_reducer::party_decline;
pub use party_invite_reducer::party_invite;
pub use party_join_reducer::party_join;
pub use party_leave_reducer::party_leave;
pub use party_member_row_type::PartyMemberRow;
pub use party_member_table::*;
pub use party_request_kind_type::PartyRequestKind;
pub use party_request_row_type::PartyRequestRow;
pub use party_request_table::*;
pub use party_row_type::PartyRow;
pub use party_table::*;
pub use periodic_effect_table::*;
pub use periodic_effect_type::PeriodicEffect;
pub use place_buy_order_reducer::place_buy_order;
pub use place_sell_order_reducer::place_sell_order;
pub use player_message_event_type::PlayerMessageEvent;
pub use player_message_table::*;
pub use player_stats_table::*;
pub use player_stats_type::PlayerStats;
pub use player_table::*;
pub use player_type::Player;
pub use projectile_table::*;
pub use projectile_type::Projectile;
pub use prop_override_table::*;
pub use prop_override_type::PropOverride;
pub use register_reducer::register;
pub use release_cast_reducer::release_cast;
pub use resonance_table::*;
pub use resonance_type::Resonance;
pub use resource_node_table::*;
pub use resource_node_type::ResourceNode;
pub use respawn_reducer::respawn;
pub use revoke_api_key_reducer::revoke_api_key;
pub use role_row_type::RoleRow;
pub use secondary_word_row_type::SecondaryWordRow;
pub use send_chat_message_reducer::send_chat_message;
pub use session_table::*;
pub use session_type::Session;
pub use set_ability_selection_reducer::set_ability_selection;
pub use set_armor_inscription_reducer::set_armor_inscription;

pub use set_resonance_xp_reducer::set_resonance_xp;
pub use set_root_inscription_reducer::set_root_inscription;
pub use slot_inscription_row_type::SlotInscriptionRow;
pub use spell_visual_effect_event_type::SpellVisualEffectEvent;
pub use spell_visual_effect_table::*;
pub use split_item_reducer::split_item;
pub use start_craft_reducer::start_craft;
pub use start_gather_reducer::start_gather;
pub use stat_modifier_table::*;
pub use stat_modifier_type::StatModifier;
pub use stats_row_type::StatsRow;
pub use stop_craft_reducer::stop_craft;
pub use stop_gather_reducer::stop_gather;
pub use stop_reducer::stop;
pub use threat_table::*;
pub use threat_type::Threat;
pub use tick_schedule_type::TickSchedule;
pub use tick_stats_table::*;
pub use tick_stats_type::TickStats;
pub use unequip_item_reducer::unequip_item;
pub use vec_3_row_type::Vec3Row;
pub use weapon_inscription_row_type::WeaponInscriptionRow;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ArmorCast {
        armor_slot: String,
        ability_slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    },
    AuthenticateApiKey {
        secret: String,
    },
    AwardResonanceXp {
        root_word_id: String,
        xp_amount: u64,
    },
    CancelBuyOrder {
        order_id: u64,
    },
    CancelSellOrder {
        order_id: u64,
    },
    CastWeapon {
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    },
    ClaimNpcItem {
        npc_entity_id: u64,
        item_id: String,
    },
    CombineItem {
        slot_index: u8,
    },
    CreateApiKey {
        id: __sdk::Uuid,
        name: String,
        prefix: String,
        secret: String,
    },
    DeleteCharacter {
        character_id: __sdk::Uuid,
    },
    DestroyItem {
        instance_id: u64,
    },
    EquipItem {
        slot_index: u8,
    },
    GmClearPropOverride {
        map_id: String,
        prop_id: String,
    },
    GmGrantGold {
        display_name: String,
        amount: u64,
    },
    GmReseedWorld,
    GmSetPropOverride {
        map_id: String,
        prop_id: String,
        position: Option<Vec3Row>,
        rotation_y: Option<f32>,
        scale: Option<Vec3Row>,
        removed: bool,
    },
    Heartbeat,
    Join {
        display_name: String,
    },
    Leave,
    Login {
        email: String,
        password: String,
    },
    Logout,
    LootTake {
        bag_id: u64,
        slot_index: u8,
    },
    LootTakeAll {
        bag_id: u64,
    },
    LootTakeGold {
        bag_id: u64,
    },
    MarketBuy {
        npc_entity_id: u64,
        sell_order_id: u64,
    },
    MarketSell {
        npc_entity_id: u64,
        instance_id: u64,
        min_price: u64,
        quantity: u32,
    },
    MoveItem {
        from: u8,
        to: u8,
    },
    MoveTo {
        x: f32,
        y: f32,
        z: f32,
    },
    PartyAccept {
        name: String,
    },
    PartyDecline {
        name: String,
    },
    PartyInvite {
        target_name: String,
    },
    PartyJoin {
        leader_name: String,
    },
    PartyLeave,
    PlaceBuyOrder {
        npc_entity_id: u64,
        item_id: String,
        price: u64,
    },
    PlaceSellOrder {
        npc_entity_id: u64,
        instance_id: u64,
        price: u64,
        quantity: u32,
    },
    Register {
        email: String,
        password: String,
    },
    ReleaseCast {
        spell_id: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    },
    Respawn,
    RevokeApiKey {
        id: __sdk::Uuid,
    },
    SendChatMessage {
        text: String,
    },
    SetAbilitySelection {
        slot: String,
        ability_id: String,
    },
    SetArmorInscription {
        slot: String,
        root_word: Option<String>,
        secondary_words: Vec<String>,
    },

    SetResonanceXp {
        root_word_id: String,
        xp: u64,
        level: u32,
    },
    SetRootInscription {
        root_word: Option<String>,
        primary_words: Vec<String>,
        secondary_words: Vec<String>,
        ultimate_words: Vec<String>,
    },
    SplitItem {
        slot_index: u8,
        amount: u32,
    },
    StartCraft {
        npc_entity_id: u64,
        item_id: String,
        quantity: u32,
    },
    StartGather {
        node_entity_id: u64,
    },
    Stop,
    StopCraft,
    StopGather,
    UnequipItem {
        slot: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ArmorCast { .. } => "armor_cast",
            Reducer::AuthenticateApiKey { .. } => "authenticate_api_key",
            Reducer::AwardResonanceXp { .. } => "award_resonance_xp",
            Reducer::CancelBuyOrder { .. } => "cancel_buy_order",
            Reducer::CancelSellOrder { .. } => "cancel_sell_order",
            Reducer::CastWeapon { .. } => "cast_weapon",
            Reducer::ClaimNpcItem { .. } => "claim_npc_item",
            Reducer::CombineItem { .. } => "combine_item",
            Reducer::CreateApiKey { .. } => "create_api_key",
            Reducer::DeleteCharacter { .. } => "delete_character",
            Reducer::DestroyItem { .. } => "destroy_item",
            Reducer::EquipItem { .. } => "equip_item",
            Reducer::GmClearPropOverride { .. } => "gm_clear_prop_override",
            Reducer::GmGrantGold { .. } => "gm_grant_gold",
            Reducer::GmReseedWorld => "gm_reseed_world",
            Reducer::GmSetPropOverride { .. } => "gm_set_prop_override",
            Reducer::Heartbeat => "heartbeat",
            Reducer::Join { .. } => "join",
            Reducer::Leave => "leave",
            Reducer::Login { .. } => "login",
            Reducer::Logout => "logout",
            Reducer::LootTake { .. } => "loot_take",
            Reducer::LootTakeAll { .. } => "loot_take_all",
            Reducer::LootTakeGold { .. } => "loot_take_gold",
            Reducer::MarketBuy { .. } => "market_buy",
            Reducer::MarketSell { .. } => "market_sell",
            Reducer::MoveItem { .. } => "move_item",
            Reducer::MoveTo { .. } => "move_to",
            Reducer::PartyAccept { .. } => "party_accept",
            Reducer::PartyDecline { .. } => "party_decline",
            Reducer::PartyInvite { .. } => "party_invite",
            Reducer::PartyJoin { .. } => "party_join",
            Reducer::PartyLeave => "party_leave",
            Reducer::PlaceBuyOrder { .. } => "place_buy_order",
            Reducer::PlaceSellOrder { .. } => "place_sell_order",
            Reducer::Register { .. } => "register",
            Reducer::ReleaseCast { .. } => "release_cast",
            Reducer::Respawn => "respawn",
            Reducer::RevokeApiKey { .. } => "revoke_api_key",
            Reducer::SendChatMessage { .. } => "send_chat_message",
            Reducer::SetAbilitySelection { .. } => "set_ability_selection",
            Reducer::SetArmorInscription { .. } => "set_armor_inscription",

            Reducer::SetResonanceXp { .. } => "set_resonance_xp",
            Reducer::SetRootInscription { .. } => "set_root_inscription",
            Reducer::SplitItem { .. } => "split_item",
            Reducer::StartCraft { .. } => "start_craft",
            Reducer::StartGather { .. } => "start_gather",
            Reducer::Stop => "stop",
            Reducer::StopCraft => "stop_craft",
            Reducer::StopGather => "stop_gather",
            Reducer::UnequipItem { .. } => "unequip_item",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ArmorCast {
                armor_slot,
                ability_slot,
                target_entity,
                target_position,
            } => __sats::bsatn::to_vec(&armor_cast_reducer::ArmorCastArgs {
                armor_slot: armor_slot.clone(),
                ability_slot: ability_slot.clone(),
                target_entity: target_entity.clone(),
                target_position: target_position.clone(),
            }),
            Reducer::AuthenticateApiKey { secret } => {
                __sats::bsatn::to_vec(&authenticate_api_key_reducer::AuthenticateApiKeyArgs {
                    secret: secret.clone(),
                })
            }
            Reducer::AwardResonanceXp {
                root_word_id,
                xp_amount,
            } => __sats::bsatn::to_vec(&award_resonance_xp_reducer::AwardResonanceXpArgs {
                root_word_id: root_word_id.clone(),
                xp_amount: xp_amount.clone(),
            }),
            Reducer::CancelBuyOrder { order_id } => {
                __sats::bsatn::to_vec(&cancel_buy_order_reducer::CancelBuyOrderArgs {
                    order_id: order_id.clone(),
                })
            }
            Reducer::CancelSellOrder { order_id } => {
                __sats::bsatn::to_vec(&cancel_sell_order_reducer::CancelSellOrderArgs {
                    order_id: order_id.clone(),
                })
            }
            Reducer::CastWeapon {
                slot,
                target_entity,
                target_position,
            } => __sats::bsatn::to_vec(&cast_weapon_reducer::CastWeaponArgs {
                slot: slot.clone(),
                target_entity: target_entity.clone(),
                target_position: target_position.clone(),
            }),
            Reducer::ClaimNpcItem {
                npc_entity_id,
                item_id,
            } => __sats::bsatn::to_vec(&claim_npc_item_reducer::ClaimNpcItemArgs {
                npc_entity_id: npc_entity_id.clone(),
                item_id: item_id.clone(),
            }),
            Reducer::CombineItem { slot_index } => {
                __sats::bsatn::to_vec(&combine_item_reducer::CombineItemArgs {
                    slot_index: slot_index.clone(),
                })
            }
            Reducer::CreateApiKey {
                id,
                name,
                prefix,
                secret,
            } => __sats::bsatn::to_vec(&create_api_key_reducer::CreateApiKeyArgs {
                id: id.clone(),
                name: name.clone(),
                prefix: prefix.clone(),
                secret: secret.clone(),
            }),
            Reducer::DeleteCharacter { character_id } => {
                __sats::bsatn::to_vec(&delete_character_reducer::DeleteCharacterArgs {
                    character_id: character_id.clone(),
                })
            }
            Reducer::DestroyItem { instance_id } => {
                __sats::bsatn::to_vec(&destroy_item_reducer::DestroyItemArgs {
                    instance_id: instance_id.clone(),
                })
            }
            Reducer::EquipItem { slot_index } => {
                __sats::bsatn::to_vec(&equip_item_reducer::EquipItemArgs {
                    slot_index: slot_index.clone(),
                })
            }
            Reducer::GmClearPropOverride { map_id, prop_id } => {
                __sats::bsatn::to_vec(&gm_clear_prop_override_reducer::GmClearPropOverrideArgs {
                    map_id: map_id.clone(),
                    prop_id: prop_id.clone(),
                })
            }
            Reducer::GmGrantGold {
                display_name,
                amount,
            } => __sats::bsatn::to_vec(&gm_grant_gold_reducer::GmGrantGoldArgs {
                display_name: display_name.clone(),
                amount: amount.clone(),
            }),
            Reducer::GmReseedWorld => {
                __sats::bsatn::to_vec(&gm_reseed_world_reducer::GmReseedWorldArgs {})
            }
            Reducer::GmSetPropOverride {
                map_id,
                prop_id,
                position,
                rotation_y,
                scale,
                removed,
            } => __sats::bsatn::to_vec(&gm_set_prop_override_reducer::GmSetPropOverrideArgs {
                map_id: map_id.clone(),
                prop_id: prop_id.clone(),
                position: position.clone(),
                rotation_y: rotation_y.clone(),
                scale: scale.clone(),
                removed: removed.clone(),
            }),
            Reducer::Heartbeat => __sats::bsatn::to_vec(&heartbeat_reducer::HeartbeatArgs {}),
            Reducer::Join { display_name } => __sats::bsatn::to_vec(&join_reducer::JoinArgs {
                display_name: display_name.clone(),
            }),
            Reducer::Leave => __sats::bsatn::to_vec(&leave_reducer::LeaveArgs {}),
            Reducer::Login { email, password } => {
                __sats::bsatn::to_vec(&login_reducer::LoginArgs {
                    email: email.clone(),
                    password: password.clone(),
                })
            }
            Reducer::Logout => __sats::bsatn::to_vec(&logout_reducer::LogoutArgs {}),
            Reducer::LootTake { bag_id, slot_index } => {
                __sats::bsatn::to_vec(&loot_take_reducer::LootTakeArgs {
                    bag_id: bag_id.clone(),
                    slot_index: slot_index.clone(),
                })
            }
            Reducer::LootTakeAll { bag_id } => {
                __sats::bsatn::to_vec(&loot_take_all_reducer::LootTakeAllArgs {
                    bag_id: bag_id.clone(),
                })
            }
            Reducer::LootTakeGold { bag_id } => {
                __sats::bsatn::to_vec(&loot_take_gold_reducer::LootTakeGoldArgs {
                    bag_id: bag_id.clone(),
                })
            }
            Reducer::MarketBuy {
                npc_entity_id,
                sell_order_id,
            } => __sats::bsatn::to_vec(&market_buy_reducer::MarketBuyArgs {
                npc_entity_id: npc_entity_id.clone(),
                sell_order_id: sell_order_id.clone(),
            }),
            Reducer::MarketSell {
                npc_entity_id,
                instance_id,
                min_price,
                quantity,
            } => __sats::bsatn::to_vec(&market_sell_reducer::MarketSellArgs {
                npc_entity_id: npc_entity_id.clone(),
                instance_id: instance_id.clone(),
                min_price: min_price.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::MoveItem { from, to } => {
                __sats::bsatn::to_vec(&move_item_reducer::MoveItemArgs {
                    from: from.clone(),
                    to: to.clone(),
                })
            }
            Reducer::MoveTo { x, y, z } => __sats::bsatn::to_vec(&move_to_reducer::MoveToArgs {
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
            }),
            Reducer::PartyAccept { name } => {
                __sats::bsatn::to_vec(&party_accept_reducer::PartyAcceptArgs { name: name.clone() })
            }
            Reducer::PartyDecline { name } => {
                __sats::bsatn::to_vec(&party_decline_reducer::PartyDeclineArgs {
                    name: name.clone(),
                })
            }
            Reducer::PartyInvite { target_name } => {
                __sats::bsatn::to_vec(&party_invite_reducer::PartyInviteArgs {
                    target_name: target_name.clone(),
                })
            }
            Reducer::PartyJoin { leader_name } => {
                __sats::bsatn::to_vec(&party_join_reducer::PartyJoinArgs {
                    leader_name: leader_name.clone(),
                })
            }
            Reducer::PartyLeave => __sats::bsatn::to_vec(&party_leave_reducer::PartyLeaveArgs {}),
            Reducer::PlaceBuyOrder {
                npc_entity_id,
                item_id,
                price,
            } => __sats::bsatn::to_vec(&place_buy_order_reducer::PlaceBuyOrderArgs {
                npc_entity_id: npc_entity_id.clone(),
                item_id: item_id.clone(),
                price: price.clone(),
            }),
            Reducer::PlaceSellOrder {
                npc_entity_id,
                instance_id,
                price,
                quantity,
            } => __sats::bsatn::to_vec(&place_sell_order_reducer::PlaceSellOrderArgs {
                npc_entity_id: npc_entity_id.clone(),
                instance_id: instance_id.clone(),
                price: price.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::Register { email, password } => {
                __sats::bsatn::to_vec(&register_reducer::RegisterArgs {
                    email: email.clone(),
                    password: password.clone(),
                })
            }
            Reducer::ReleaseCast {
                spell_id,
                target_entity,
                target_position,
            } => __sats::bsatn::to_vec(&release_cast_reducer::ReleaseCastArgs {
                spell_id: spell_id.clone(),
                target_entity: target_entity.clone(),
                target_position: target_position.clone(),
            }),
            Reducer::Respawn => __sats::bsatn::to_vec(&respawn_reducer::RespawnArgs {}),
            Reducer::RevokeApiKey { id } => {
                __sats::bsatn::to_vec(&revoke_api_key_reducer::RevokeApiKeyArgs { id: id.clone() })
            }
            Reducer::SendChatMessage { text } => {
                __sats::bsatn::to_vec(&send_chat_message_reducer::SendChatMessageArgs {
                    text: text.clone(),
                })
            }
            Reducer::SetAbilitySelection { slot, ability_id } => {
                __sats::bsatn::to_vec(&set_ability_selection_reducer::SetAbilitySelectionArgs {
                    slot: slot.clone(),
                    ability_id: ability_id.clone(),
                })
            }
            Reducer::SetArmorInscription {
                slot,
                root_word,
                secondary_words,
            } => __sats::bsatn::to_vec(&set_armor_inscription_reducer::SetArmorInscriptionArgs {
                slot: slot.clone(),
                root_word: root_word.clone(),
                secondary_words: secondary_words.clone(),
            }),

            Reducer::SetResonanceXp {
                root_word_id,
                xp,
                level,
            } => __sats::bsatn::to_vec(&set_resonance_xp_reducer::SetResonanceXpArgs {
                root_word_id: root_word_id.clone(),
                xp: xp.clone(),
                level: level.clone(),
            }),
            Reducer::SetRootInscription {
                root_word,
                primary_words,
                secondary_words,
                ultimate_words,
            } => __sats::bsatn::to_vec(&set_root_inscription_reducer::SetRootInscriptionArgs {
                root_word: root_word.clone(),
                primary_words: primary_words.clone(),
                secondary_words: secondary_words.clone(),
                ultimate_words: ultimate_words.clone(),
            }),
            Reducer::SplitItem { slot_index, amount } => {
                __sats::bsatn::to_vec(&split_item_reducer::SplitItemArgs {
                    slot_index: slot_index.clone(),
                    amount: amount.clone(),
                })
            }
            Reducer::StartCraft {
                npc_entity_id,
                item_id,
                quantity,
            } => __sats::bsatn::to_vec(&start_craft_reducer::StartCraftArgs {
                npc_entity_id: npc_entity_id.clone(),
                item_id: item_id.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::StartGather { node_entity_id } => {
                __sats::bsatn::to_vec(&start_gather_reducer::StartGatherArgs {
                    node_entity_id: node_entity_id.clone(),
                })
            }
            Reducer::Stop => __sats::bsatn::to_vec(&stop_reducer::StopArgs {}),
            Reducer::StopCraft => __sats::bsatn::to_vec(&stop_craft_reducer::StopCraftArgs {}),
            Reducer::StopGather => __sats::bsatn::to_vec(&stop_gather_reducer::StopGatherArgs {}),
            Reducer::UnequipItem { slot } => {
                __sats::bsatn::to_vec(&unequip_item_reducer::UnequipItemArgs { slot: slot.clone() })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    account_economy: __sdk::TableUpdate<AccountEconomy>,
    active_status: __sdk::TableUpdate<ActiveStatus>,
    aoe_region: __sdk::TableUpdate<AoeRegion>,
    boss_state: __sdk::TableUpdate<BossState>,
    cast_ended: __sdk::TableUpdate<CastEndedEvent>,
    cast_state: __sdk::TableUpdate<CastState>,
    character_wallet: __sdk::TableUpdate<CharacterWallet>,
    cooldown: __sdk::TableUpdate<Cooldown>,
    craft_session: __sdk::TableUpdate<CraftSession>,
    crowd_control: __sdk::TableUpdate<CrowdControl>,
    damage_event: __sdk::TableUpdate<DamageEventRow>,
    enemy_ai: __sdk::TableUpdate<EnemyAi>,
    entity_stats: __sdk::TableUpdate<EntityStats>,
    equipment: __sdk::TableUpdate<EquipmentTable>,
    game_entity: __sdk::TableUpdate<GameEntity>,
    gather_session: __sdk::TableUpdate<GatherSession>,
    gather_yield: __sdk::TableUpdate<GatherYieldEvent>,
    hotbar: __sdk::TableUpdate<Hotbar>,
    inventory: __sdk::TableUpdate<InventoryTable>,
    known_ancient_language: __sdk::TableUpdate<KnownAncientLanguageTable>,
    loot_bag: __sdk::TableUpdate<LootBag>,
    loot_bag_slot: __sdk::TableUpdate<LootBagSlot>,
    market: __sdk::TableUpdate<Market>,
    market_buy_order: __sdk::TableUpdate<MarketBuyOrder>,
    market_sell_order: __sdk::TableUpdate<MarketSellOrder>,
    my_api_keys: __sdk::TableUpdate<ApiKeyMeta>,
    npc: __sdk::TableUpdate<Npc>,
    party: __sdk::TableUpdate<PartyRow>,
    party_member: __sdk::TableUpdate<PartyMemberRow>,
    party_request: __sdk::TableUpdate<PartyRequestRow>,
    periodic_effect: __sdk::TableUpdate<PeriodicEffect>,
    player: __sdk::TableUpdate<Player>,
    player_message: __sdk::TableUpdate<PlayerMessageEvent>,
    player_stats: __sdk::TableUpdate<PlayerStats>,
    projectile: __sdk::TableUpdate<Projectile>,
    prop_override: __sdk::TableUpdate<PropOverride>,
    resonance: __sdk::TableUpdate<Resonance>,
    resource_node: __sdk::TableUpdate<ResourceNode>,
    session: __sdk::TableUpdate<Session>,
    spell_visual_effect: __sdk::TableUpdate<SpellVisualEffectEvent>,
    stat_modifier: __sdk::TableUpdate<StatModifier>,
    threat: __sdk::TableUpdate<Threat>,
    tick_stats: __sdk::TableUpdate<TickStats>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "account_economy" => db_update
                    .account_economy
                    .append(account_economy_table::parse_table_update(table_update)?),
                "active_status" => db_update
                    .active_status
                    .append(active_status_table::parse_table_update(table_update)?),
                "aoe_region" => db_update
                    .aoe_region
                    .append(aoe_region_table::parse_table_update(table_update)?),
                "boss_state" => db_update
                    .boss_state
                    .append(boss_state_table::parse_table_update(table_update)?),
                "cast_ended" => db_update
                    .cast_ended
                    .append(cast_ended_table::parse_table_update(table_update)?),
                "cast_state" => db_update
                    .cast_state
                    .append(cast_state_table::parse_table_update(table_update)?),
                "character_wallet" => db_update
                    .character_wallet
                    .append(character_wallet_table::parse_table_update(table_update)?),
                "cooldown" => db_update
                    .cooldown
                    .append(cooldown_table::parse_table_update(table_update)?),
                "craft_session" => db_update
                    .craft_session
                    .append(craft_session_table::parse_table_update(table_update)?),
                "crowd_control" => db_update
                    .crowd_control
                    .append(crowd_control_table::parse_table_update(table_update)?),
                "damage_event" => db_update
                    .damage_event
                    .append(damage_event_table::parse_table_update(table_update)?),
                "enemy_ai" => db_update
                    .enemy_ai
                    .append(enemy_ai_table::parse_table_update(table_update)?),
                "entity_stats" => db_update
                    .entity_stats
                    .append(entity_stats_table::parse_table_update(table_update)?),
                "equipment" => db_update
                    .equipment
                    .append(equipment_table::parse_table_update(table_update)?),
                "game_entity" => db_update
                    .game_entity
                    .append(game_entity_table::parse_table_update(table_update)?),
                "gather_session" => db_update
                    .gather_session
                    .append(gather_session_table::parse_table_update(table_update)?),
                "gather_yield" => db_update
                    .gather_yield
                    .append(gather_yield_table::parse_table_update(table_update)?),
                "hotbar" => db_update
                    .hotbar
                    .append(hotbar_table::parse_table_update(table_update)?),
                "inventory" => db_update
                    .inventory
                    .append(inventory_table::parse_table_update(table_update)?),
                "known_ancient_language" => db_update.known_ancient_language.append(
                    known_ancient_language_table::parse_table_update(table_update)?,
                ),
                "loot_bag" => db_update
                    .loot_bag
                    .append(loot_bag_table::parse_table_update(table_update)?),
                "loot_bag_slot" => db_update
                    .loot_bag_slot
                    .append(loot_bag_slot_table::parse_table_update(table_update)?),
                "market" => db_update
                    .market
                    .append(market_table::parse_table_update(table_update)?),
                "market_buy_order" => db_update
                    .market_buy_order
                    .append(market_buy_order_table::parse_table_update(table_update)?),
                "market_sell_order" => db_update
                    .market_sell_order
                    .append(market_sell_order_table::parse_table_update(table_update)?),
                "my_api_keys" => db_update
                    .my_api_keys
                    .append(my_api_keys_table::parse_table_update(table_update)?),
                "npc" => db_update
                    .npc
                    .append(npc_table::parse_table_update(table_update)?),
                "party" => db_update
                    .party
                    .append(party_table::parse_table_update(table_update)?),
                "party_member" => db_update
                    .party_member
                    .append(party_member_table::parse_table_update(table_update)?),
                "party_request" => db_update
                    .party_request
                    .append(party_request_table::parse_table_update(table_update)?),
                "periodic_effect" => db_update
                    .periodic_effect
                    .append(periodic_effect_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_message" => db_update
                    .player_message
                    .append(player_message_table::parse_table_update(table_update)?),
                "player_stats" => db_update
                    .player_stats
                    .append(player_stats_table::parse_table_update(table_update)?),
                "projectile" => db_update
                    .projectile
                    .append(projectile_table::parse_table_update(table_update)?),
                "prop_override" => db_update
                    .prop_override
                    .append(prop_override_table::parse_table_update(table_update)?),
                "resonance" => db_update
                    .resonance
                    .append(resonance_table::parse_table_update(table_update)?),
                "resource_node" => db_update
                    .resource_node
                    .append(resource_node_table::parse_table_update(table_update)?),
                "session" => db_update
                    .session
                    .append(session_table::parse_table_update(table_update)?),
                "spell_visual_effect" => db_update
                    .spell_visual_effect
                    .append(spell_visual_effect_table::parse_table_update(table_update)?),
                "stat_modifier" => db_update
                    .stat_modifier
                    .append(stat_modifier_table::parse_table_update(table_update)?),
                "threat" => db_update
                    .threat
                    .append(threat_table::parse_table_update(table_update)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(tick_stats_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.account_economy = cache
            .apply_diff_to_table::<AccountEconomy>("account_economy", &self.account_economy)
            .with_updates_by_pk(|row| &row.account_id);
        diff.active_status = cache
            .apply_diff_to_table::<ActiveStatus>("active_status", &self.active_status)
            .with_updates_by_pk(|row| &row.id);
        diff.aoe_region = cache
            .apply_diff_to_table::<AoeRegion>("aoe_region", &self.aoe_region)
            .with_updates_by_pk(|row| &row.id);
        diff.boss_state = cache
            .apply_diff_to_table::<BossState>("boss_state", &self.boss_state)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.cast_ended = self.cast_ended.into_event_diff();
        diff.cast_state = cache
            .apply_diff_to_table::<CastState>("cast_state", &self.cast_state)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.character_wallet = cache
            .apply_diff_to_table::<CharacterWallet>("character_wallet", &self.character_wallet)
            .with_updates_by_pk(|row| &row.character_id);
        diff.cooldown = cache
            .apply_diff_to_table::<Cooldown>("cooldown", &self.cooldown)
            .with_updates_by_pk(|row| &row.id);
        diff.craft_session = cache
            .apply_diff_to_table::<CraftSession>("craft_session", &self.craft_session)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.crowd_control = cache
            .apply_diff_to_table::<CrowdControl>("crowd_control", &self.crowd_control)
            .with_updates_by_pk(|row| &row.id);
        diff.damage_event = self.damage_event.into_event_diff();
        diff.enemy_ai = cache
            .apply_diff_to_table::<EnemyAi>("enemy_ai", &self.enemy_ai)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.entity_stats = cache
            .apply_diff_to_table::<EntityStats>("entity_stats", &self.entity_stats)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.equipment = cache
            .apply_diff_to_table::<EquipmentTable>("equipment", &self.equipment)
            .with_updates_by_pk(|row| &row.character_id);
        diff.game_entity = cache
            .apply_diff_to_table::<GameEntity>("game_entity", &self.game_entity)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.gather_session = cache
            .apply_diff_to_table::<GatherSession>("gather_session", &self.gather_session)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.gather_yield = self.gather_yield.into_event_diff();
        diff.hotbar = cache
            .apply_diff_to_table::<Hotbar>("hotbar", &self.hotbar)
            .with_updates_by_pk(|row| &row.character_id);
        diff.inventory = cache
            .apply_diff_to_table::<InventoryTable>("inventory", &self.inventory)
            .with_updates_by_pk(|row| &row.character_id);
        diff.known_ancient_language = cache
            .apply_diff_to_table::<KnownAncientLanguageTable>(
                "known_ancient_language",
                &self.known_ancient_language,
            )
            .with_updates_by_pk(|row| &row.character_id);
        diff.loot_bag = cache
            .apply_diff_to_table::<LootBag>("loot_bag", &self.loot_bag)
            .with_updates_by_pk(|row| &row.id);
        diff.loot_bag_slot = cache
            .apply_diff_to_table::<LootBagSlot>("loot_bag_slot", &self.loot_bag_slot)
            .with_updates_by_pk(|row| &row.id);
        diff.market = cache
            .apply_diff_to_table::<Market>("market", &self.market)
            .with_updates_by_pk(|row| &row.id);
        diff.market_buy_order = cache
            .apply_diff_to_table::<MarketBuyOrder>("market_buy_order", &self.market_buy_order)
            .with_updates_by_pk(|row| &row.id);
        diff.market_sell_order = cache
            .apply_diff_to_table::<MarketSellOrder>("market_sell_order", &self.market_sell_order)
            .with_updates_by_pk(|row| &row.id);
        diff.npc = cache
            .apply_diff_to_table::<Npc>("npc", &self.npc)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.party = cache
            .apply_diff_to_table::<PartyRow>("party", &self.party)
            .with_updates_by_pk(|row| &row.party_id);
        diff.party_member = cache
            .apply_diff_to_table::<PartyMemberRow>("party_member", &self.party_member)
            .with_updates_by_pk(|row| &row.character_id);
        diff.party_request = cache
            .apply_diff_to_table::<PartyRequestRow>("party_request", &self.party_request)
            .with_updates_by_pk(|row| &row.request_id);
        diff.periodic_effect = cache
            .apply_diff_to_table::<PeriodicEffect>("periodic_effect", &self.periodic_effect)
            .with_updates_by_pk(|row| &row.id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.character_id);
        diff.player_message = self.player_message.into_event_diff();
        diff.player_stats = cache
            .apply_diff_to_table::<PlayerStats>("player_stats", &self.player_stats)
            .with_updates_by_pk(|row| &row.character_id);
        diff.projectile = cache
            .apply_diff_to_table::<Projectile>("projectile", &self.projectile)
            .with_updates_by_pk(|row| &row.id);
        diff.prop_override = cache
            .apply_diff_to_table::<PropOverride>("prop_override", &self.prop_override)
            .with_updates_by_pk(|row| &row.id);
        diff.resonance = cache
            .apply_diff_to_table::<Resonance>("resonance", &self.resonance)
            .with_updates_by_pk(|row| &row.id);
        diff.resource_node = cache
            .apply_diff_to_table::<ResourceNode>("resource_node", &self.resource_node)
            .with_updates_by_pk(|row| &row.placement_id);
        diff.session = cache
            .apply_diff_to_table::<Session>("session", &self.session)
            .with_updates_by_pk(|row| &row.identity);
        diff.spell_visual_effect = self.spell_visual_effect.into_event_diff();
        diff.stat_modifier = cache
            .apply_diff_to_table::<StatModifier>("stat_modifier", &self.stat_modifier)
            .with_updates_by_pk(|row| &row.id);
        diff.threat = cache
            .apply_diff_to_table::<Threat>("threat", &self.threat)
            .with_updates_by_pk(|row| &row.id);
        diff.tick_stats = cache
            .apply_diff_to_table::<TickStats>("tick_stats", &self.tick_stats)
            .with_updates_by_pk(|row| &row.id);
        diff.my_api_keys = cache
            .apply_diff_to_table::<ApiKeyMeta>("my_api_keys", &self.my_api_keys)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "account_economy" => db_update
                    .account_economy
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "active_status" => db_update
                    .active_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "aoe_region" => db_update
                    .aoe_region
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "boss_state" => db_update
                    .boss_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cast_ended" => db_update
                    .cast_ended
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cast_state" => db_update
                    .cast_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "character_wallet" => db_update
                    .character_wallet
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cooldown" => db_update
                    .cooldown
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "craft_session" => db_update
                    .craft_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "crowd_control" => db_update
                    .crowd_control
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "enemy_ai" => db_update
                    .enemy_ai
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "entity_stats" => db_update
                    .entity_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "equipment" => db_update
                    .equipment
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_entity" => db_update
                    .game_entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gather_session" => db_update
                    .gather_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gather_yield" => db_update
                    .gather_yield
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hotbar" => db_update
                    .hotbar
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "known_ancient_language" => db_update
                    .known_ancient_language
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "loot_bag" => db_update
                    .loot_bag
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "loot_bag_slot" => db_update
                    .loot_bag_slot
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "market" => db_update
                    .market
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "market_buy_order" => db_update
                    .market_buy_order
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "market_sell_order" => db_update
                    .market_sell_order
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_api_keys" => db_update
                    .my_api_keys
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "npc" => db_update
                    .npc
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "party" => db_update
                    .party
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "party_member" => db_update
                    .party_member
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "party_request" => db_update
                    .party_request
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "periodic_effect" => db_update
                    .periodic_effect
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_message" => db_update
                    .player_message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_stats" => db_update
                    .player_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "projectile" => db_update
                    .projectile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "prop_override" => db_update
                    .prop_override
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resonance" => db_update
                    .resonance
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resource_node" => db_update
                    .resource_node
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "session" => db_update
                    .session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "spell_visual_effect" => db_update
                    .spell_visual_effect
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "stat_modifier" => db_update
                    .stat_modifier
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "threat" => db_update
                    .threat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "account_economy" => db_update
                    .account_economy
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "active_status" => db_update
                    .active_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "aoe_region" => db_update
                    .aoe_region
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "boss_state" => db_update
                    .boss_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cast_ended" => db_update
                    .cast_ended
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cast_state" => db_update
                    .cast_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "character_wallet" => db_update
                    .character_wallet
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cooldown" => db_update
                    .cooldown
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "craft_session" => db_update
                    .craft_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "crowd_control" => db_update
                    .crowd_control
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "enemy_ai" => db_update
                    .enemy_ai
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "entity_stats" => db_update
                    .entity_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "equipment" => db_update
                    .equipment
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_entity" => db_update
                    .game_entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gather_session" => db_update
                    .gather_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gather_yield" => db_update
                    .gather_yield
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hotbar" => db_update
                    .hotbar
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "known_ancient_language" => db_update
                    .known_ancient_language
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "loot_bag" => db_update
                    .loot_bag
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "loot_bag_slot" => db_update
                    .loot_bag_slot
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "market" => db_update
                    .market
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "market_buy_order" => db_update
                    .market_buy_order
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "market_sell_order" => db_update
                    .market_sell_order
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_api_keys" => db_update
                    .my_api_keys
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "npc" => db_update
                    .npc
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "party" => db_update
                    .party
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "party_member" => db_update
                    .party_member
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "party_request" => db_update
                    .party_request
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "periodic_effect" => db_update
                    .periodic_effect
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_message" => db_update
                    .player_message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_stats" => db_update
                    .player_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "projectile" => db_update
                    .projectile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "prop_override" => db_update
                    .prop_override
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resonance" => db_update
                    .resonance
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resource_node" => db_update
                    .resource_node
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "session" => db_update
                    .session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "spell_visual_effect" => db_update
                    .spell_visual_effect
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "stat_modifier" => db_update
                    .stat_modifier
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "threat" => db_update
                    .threat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    account_economy: __sdk::TableAppliedDiff<'r, AccountEconomy>,
    active_status: __sdk::TableAppliedDiff<'r, ActiveStatus>,
    aoe_region: __sdk::TableAppliedDiff<'r, AoeRegion>,
    boss_state: __sdk::TableAppliedDiff<'r, BossState>,
    cast_ended: __sdk::TableAppliedDiff<'r, CastEndedEvent>,
    cast_state: __sdk::TableAppliedDiff<'r, CastState>,
    character_wallet: __sdk::TableAppliedDiff<'r, CharacterWallet>,
    cooldown: __sdk::TableAppliedDiff<'r, Cooldown>,
    craft_session: __sdk::TableAppliedDiff<'r, CraftSession>,
    crowd_control: __sdk::TableAppliedDiff<'r, CrowdControl>,
    damage_event: __sdk::TableAppliedDiff<'r, DamageEventRow>,
    enemy_ai: __sdk::TableAppliedDiff<'r, EnemyAi>,
    entity_stats: __sdk::TableAppliedDiff<'r, EntityStats>,
    equipment: __sdk::TableAppliedDiff<'r, EquipmentTable>,
    game_entity: __sdk::TableAppliedDiff<'r, GameEntity>,
    gather_session: __sdk::TableAppliedDiff<'r, GatherSession>,
    gather_yield: __sdk::TableAppliedDiff<'r, GatherYieldEvent>,
    hotbar: __sdk::TableAppliedDiff<'r, Hotbar>,
    inventory: __sdk::TableAppliedDiff<'r, InventoryTable>,
    known_ancient_language: __sdk::TableAppliedDiff<'r, KnownAncientLanguageTable>,
    loot_bag: __sdk::TableAppliedDiff<'r, LootBag>,
    loot_bag_slot: __sdk::TableAppliedDiff<'r, LootBagSlot>,
    market: __sdk::TableAppliedDiff<'r, Market>,
    market_buy_order: __sdk::TableAppliedDiff<'r, MarketBuyOrder>,
    market_sell_order: __sdk::TableAppliedDiff<'r, MarketSellOrder>,
    my_api_keys: __sdk::TableAppliedDiff<'r, ApiKeyMeta>,
    npc: __sdk::TableAppliedDiff<'r, Npc>,
    party: __sdk::TableAppliedDiff<'r, PartyRow>,
    party_member: __sdk::TableAppliedDiff<'r, PartyMemberRow>,
    party_request: __sdk::TableAppliedDiff<'r, PartyRequestRow>,
    periodic_effect: __sdk::TableAppliedDiff<'r, PeriodicEffect>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_message: __sdk::TableAppliedDiff<'r, PlayerMessageEvent>,
    player_stats: __sdk::TableAppliedDiff<'r, PlayerStats>,
    projectile: __sdk::TableAppliedDiff<'r, Projectile>,
    prop_override: __sdk::TableAppliedDiff<'r, PropOverride>,
    resonance: __sdk::TableAppliedDiff<'r, Resonance>,
    resource_node: __sdk::TableAppliedDiff<'r, ResourceNode>,
    session: __sdk::TableAppliedDiff<'r, Session>,
    spell_visual_effect: __sdk::TableAppliedDiff<'r, SpellVisualEffectEvent>,
    stat_modifier: __sdk::TableAppliedDiff<'r, StatModifier>,
    threat: __sdk::TableAppliedDiff<'r, Threat>,
    tick_stats: __sdk::TableAppliedDiff<'r, TickStats>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AccountEconomy>(
            "account_economy",
            &self.account_economy,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ActiveStatus>(
            "active_status",
            &self.active_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AoeRegion>("aoe_region", &self.aoe_region, event);
        callbacks.invoke_table_row_callbacks::<BossState>("boss_state", &self.boss_state, event);
        callbacks.invoke_table_row_callbacks::<CastEndedEvent>(
            "cast_ended",
            &self.cast_ended,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CastState>("cast_state", &self.cast_state, event);
        callbacks.invoke_table_row_callbacks::<CharacterWallet>(
            "character_wallet",
            &self.character_wallet,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Cooldown>("cooldown", &self.cooldown, event);
        callbacks.invoke_table_row_callbacks::<CraftSession>(
            "craft_session",
            &self.craft_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CrowdControl>(
            "crowd_control",
            &self.crowd_control,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DamageEventRow>(
            "damage_event",
            &self.damage_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EnemyAi>("enemy_ai", &self.enemy_ai, event);
        callbacks.invoke_table_row_callbacks::<EntityStats>(
            "entity_stats",
            &self.entity_stats,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EquipmentTable>("equipment", &self.equipment, event);
        callbacks.invoke_table_row_callbacks::<GameEntity>("game_entity", &self.game_entity, event);
        callbacks.invoke_table_row_callbacks::<GatherSession>(
            "gather_session",
            &self.gather_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatherYieldEvent>(
            "gather_yield",
            &self.gather_yield,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Hotbar>("hotbar", &self.hotbar, event);
        callbacks.invoke_table_row_callbacks::<InventoryTable>("inventory", &self.inventory, event);
        callbacks.invoke_table_row_callbacks::<KnownAncientLanguageTable>(
            "known_ancient_language",
            &self.known_ancient_language,
            event,
        );
        callbacks.invoke_table_row_callbacks::<LootBag>("loot_bag", &self.loot_bag, event);
        callbacks.invoke_table_row_callbacks::<LootBagSlot>(
            "loot_bag_slot",
            &self.loot_bag_slot,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Market>("market", &self.market, event);
        callbacks.invoke_table_row_callbacks::<MarketBuyOrder>(
            "market_buy_order",
            &self.market_buy_order,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MarketSellOrder>(
            "market_sell_order",
            &self.market_sell_order,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ApiKeyMeta>("my_api_keys", &self.my_api_keys, event);
        callbacks.invoke_table_row_callbacks::<Npc>("npc", &self.npc, event);
        callbacks.invoke_table_row_callbacks::<PartyRow>("party", &self.party, event);
        callbacks.invoke_table_row_callbacks::<PartyMemberRow>(
            "party_member",
            &self.party_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PartyRequestRow>(
            "party_request",
            &self.party_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PeriodicEffect>(
            "periodic_effect",
            &self.periodic_effect,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerMessageEvent>(
            "player_message",
            &self.player_message,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerStats>(
            "player_stats",
            &self.player_stats,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Projectile>("projectile", &self.projectile, event);
        callbacks.invoke_table_row_callbacks::<PropOverride>(
            "prop_override",
            &self.prop_override,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Resonance>("resonance", &self.resonance, event);
        callbacks.invoke_table_row_callbacks::<ResourceNode>(
            "resource_node",
            &self.resource_node,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Session>("session", &self.session, event);
        callbacks.invoke_table_row_callbacks::<SpellVisualEffectEvent>(
            "spell_visual_effect",
            &self.spell_visual_effect,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StatModifier>(
            "stat_modifier",
            &self.stat_modifier,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Threat>("threat", &self.threat, event);
        callbacks.invoke_table_row_callbacks::<TickStats>("tick_stats", &self.tick_stats, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        account_economy_table::register_table(client_cache);
        active_status_table::register_table(client_cache);
        aoe_region_table::register_table(client_cache);
        boss_state_table::register_table(client_cache);
        cast_ended_table::register_table(client_cache);
        cast_state_table::register_table(client_cache);
        character_wallet_table::register_table(client_cache);
        cooldown_table::register_table(client_cache);
        craft_session_table::register_table(client_cache);
        crowd_control_table::register_table(client_cache);
        damage_event_table::register_table(client_cache);
        enemy_ai_table::register_table(client_cache);
        entity_stats_table::register_table(client_cache);
        equipment_table::register_table(client_cache);
        game_entity_table::register_table(client_cache);
        gather_session_table::register_table(client_cache);
        gather_yield_table::register_table(client_cache);
        hotbar_table::register_table(client_cache);
        inventory_table::register_table(client_cache);
        known_ancient_language_table::register_table(client_cache);
        loot_bag_table::register_table(client_cache);
        loot_bag_slot_table::register_table(client_cache);
        market_table::register_table(client_cache);
        market_buy_order_table::register_table(client_cache);
        market_sell_order_table::register_table(client_cache);
        my_api_keys_table::register_table(client_cache);
        npc_table::register_table(client_cache);
        party_table::register_table(client_cache);
        party_member_table::register_table(client_cache);
        party_request_table::register_table(client_cache);
        periodic_effect_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_message_table::register_table(client_cache);
        player_stats_table::register_table(client_cache);
        projectile_table::register_table(client_cache);
        prop_override_table::register_table(client_cache);
        resonance_table::register_table(client_cache);
        resource_node_table::register_table(client_cache);
        session_table::register_table(client_cache);
        spell_visual_effect_table::register_table(client_cache);
        stat_modifier_table::register_table(client_cache);
        threat_table::register_table(client_cache);
        tick_stats_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "account_economy",
        "active_status",
        "aoe_region",
        "boss_state",
        "cast_ended",
        "cast_state",
        "character_wallet",
        "cooldown",
        "craft_session",
        "crowd_control",
        "damage_event",
        "enemy_ai",
        "entity_stats",
        "equipment",
        "game_entity",
        "gather_session",
        "gather_yield",
        "hotbar",
        "inventory",
        "known_ancient_language",
        "loot_bag",
        "loot_bag_slot",
        "market",
        "market_buy_order",
        "market_sell_order",
        "my_api_keys",
        "npc",
        "party",
        "party_member",
        "party_request",
        "periodic_effect",
        "player",
        "player_message",
        "player_stats",
        "projectile",
        "prop_override",
        "resonance",
        "resource_node",
        "session",
        "spell_visual_effect",
        "stat_modifier",
        "threat",
        "tick_stats",
    ];
}
