// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::equipment_table_type::EquipmentTable;
use super::item_instance_row_type::ItemInstanceRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_equipment`.
///
/// Obtain a handle from the [`MyEquipmentTableAccess::my_equipment`] method on [`super::RemoteTables`],
/// like `ctx.db.my_equipment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_equipment().on_insert(...)`.
pub struct MyEquipmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<EquipmentTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_equipment`.
pub struct MyEquipmentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyEquipmentTableAccessor {
    type Row = EquipmentTable;
    type Handle<'db> = MyEquipmentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_equipment()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_equipment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyEquipmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyEquipmentTableHandle`], which mediates access to the table `my_equipment`.
    fn my_equipment(&self) -> MyEquipmentTableHandle<'_>;
}

impl MyEquipmentTableAccess for super::RemoteTables {
    fn my_equipment(&self) -> MyEquipmentTableHandle<'_> {
        MyEquipmentTableHandle {
            imp: self.imp.get_table::<EquipmentTable>("my_equipment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyEquipmentInsertCallbackId(__sdk::CallbackId);
pub struct MyEquipmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyEquipmentTableHandle<'ctx> {
    type Row = EquipmentTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EquipmentTable> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyEquipmentTableHandle<'ctx> {
    type Row = EquipmentTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EquipmentTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyEquipmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyEquipmentInsertCallbackId {
        MyEquipmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyEquipmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyEquipmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyEquipmentDeleteCallbackId {
        MyEquipmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyEquipmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyEquipmentTableHandle<'ctx> {
    type InsertCallbackId = MyEquipmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyEquipmentInsertCallbackId {
        MyEquipmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyEquipmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyEquipmentTableHandle<'ctx> {
    type DeleteCallbackId = MyEquipmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyEquipmentDeleteCallbackId {
        MyEquipmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyEquipmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyEquipmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyEquipmentTableHandle<'ctx> {
    type UpdateCallbackId = MyEquipmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyEquipmentUpdateCallbackId {
        MyEquipmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyEquipmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyEquipmentTableHandle<'ctx> {
    type UpdateCallbackId = MyEquipmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyEquipmentUpdateCallbackId {
        MyEquipmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyEquipmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EquipmentTable>("my_equipment");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EquipmentTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EquipmentTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EquipmentTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_equipmentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EquipmentTable`.
    fn my_equipment(&self) -> __sdk::__query_builder::Table<EquipmentTable>;
}

impl my_equipmentQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_equipment(&self) -> __sdk::__query_builder::Table<EquipmentTable> {
        __sdk::__query_builder::Table::new("my_equipment")
    }
}
