// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_stats_type::PlayerStats;
use super::stats_row_type::StatsRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_player_stats`.
///
/// Obtain a handle from the [`MyPlayerStatsTableAccess::my_player_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.my_player_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_player_stats().on_insert(...)`.
pub struct MyPlayerStatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_player_stats`.
pub struct MyPlayerStatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyPlayerStatsTableAccessor {
    type Row = PlayerStats;
    type Handle<'db> = MyPlayerStatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_player_stats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_player_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyPlayerStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyPlayerStatsTableHandle`], which mediates access to the table `my_player_stats`.
    fn my_player_stats(&self) -> MyPlayerStatsTableHandle<'_>;
}

impl MyPlayerStatsTableAccess for super::RemoteTables {
    fn my_player_stats(&self) -> MyPlayerStatsTableHandle<'_> {
        MyPlayerStatsTableHandle {
            imp: self.imp.get_table::<PlayerStats>("my_player_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyPlayerStatsInsertCallbackId(__sdk::CallbackId);
pub struct MyPlayerStatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyPlayerStatsTableHandle<'ctx> {
    type Row = PlayerStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerStats> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyPlayerStatsTableHandle<'ctx> {
    type Row = PlayerStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyPlayerStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPlayerStatsInsertCallbackId {
        MyPlayerStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyPlayerStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyPlayerStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPlayerStatsDeleteCallbackId {
        MyPlayerStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyPlayerStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyPlayerStatsTableHandle<'ctx> {
    type InsertCallbackId = MyPlayerStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPlayerStatsInsertCallbackId {
        MyPlayerStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyPlayerStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyPlayerStatsTableHandle<'ctx> {
    type DeleteCallbackId = MyPlayerStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPlayerStatsDeleteCallbackId {
        MyPlayerStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyPlayerStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyPlayerStatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyPlayerStatsTableHandle<'ctx> {
    type UpdateCallbackId = MyPlayerStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyPlayerStatsUpdateCallbackId {
        MyPlayerStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyPlayerStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyPlayerStatsTableHandle<'ctx> {
    type UpdateCallbackId = MyPlayerStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyPlayerStatsUpdateCallbackId {
        MyPlayerStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyPlayerStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerStats>("my_player_stats");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerStats>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerStats>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerStats`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_player_statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerStats`.
    fn my_player_stats(&self) -> __sdk::__query_builder::Table<PlayerStats>;
}

impl my_player_statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_player_stats(&self) -> __sdk::__query_builder::Table<PlayerStats> {
        __sdk::__query_builder::Table::new("my_player_stats")
    }
}
