// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_request_kind_type::PartyRequestKind;
use super::party_request_row_type::PartyRequestRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_party_requests`.
///
/// Obtain a handle from the [`MyPartyRequestsTableAccess::my_party_requests`] method on [`super::RemoteTables`],
/// like `ctx.db.my_party_requests()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_party_requests().on_insert(...)`.
pub struct MyPartyRequestsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyRequestRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_party_requests`.
pub struct MyPartyRequestsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyPartyRequestsTableAccessor {
    type Row = PartyRequestRow;
    type Handle<'db> = MyPartyRequestsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_party_requests()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_party_requests`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyPartyRequestsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyPartyRequestsTableHandle`], which mediates access to the table `my_party_requests`.
    fn my_party_requests(&self) -> MyPartyRequestsTableHandle<'_>;
}

impl MyPartyRequestsTableAccess for super::RemoteTables {
    fn my_party_requests(&self) -> MyPartyRequestsTableHandle<'_> {
        MyPartyRequestsTableHandle {
            imp: self.imp.get_table::<PartyRequestRow>("my_party_requests"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyPartyRequestsInsertCallbackId(__sdk::CallbackId);
pub struct MyPartyRequestsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyPartyRequestsTableHandle<'ctx> {
    type Row = PartyRequestRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyRequestRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyPartyRequestsTableHandle<'ctx> {
    type Row = PartyRequestRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyRequestRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyPartyRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPartyRequestsInsertCallbackId {
        MyPartyRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyPartyRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyPartyRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPartyRequestsDeleteCallbackId {
        MyPartyRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyPartyRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyPartyRequestsTableHandle<'ctx> {
    type InsertCallbackId = MyPartyRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPartyRequestsInsertCallbackId {
        MyPartyRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyPartyRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyPartyRequestsTableHandle<'ctx> {
    type DeleteCallbackId = MyPartyRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyPartyRequestsDeleteCallbackId {
        MyPartyRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyPartyRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyPartyRequestsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyPartyRequestsTableHandle<'ctx> {
    type UpdateCallbackId = MyPartyRequestsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyPartyRequestsUpdateCallbackId {
        MyPartyRequestsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyPartyRequestsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyPartyRequestsTableHandle<'ctx> {
    type UpdateCallbackId = MyPartyRequestsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyPartyRequestsUpdateCallbackId {
        MyPartyRequestsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyPartyRequestsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `request_id` unique index on the table `my_party_requests`,
/// which allows point queries on the field of the same name
/// via the [`MyPartyRequestsRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_party_requests().request_id().find(...)`.
pub struct MyPartyRequestsRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PartyRequestRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyPartyRequestsTableHandle<'ctx> {
    /// Get a handle on the `request_id` unique index on the table `my_party_requests`.
    pub fn request_id(&self) -> MyPartyRequestsRequestIdUnique<'ctx> {
        MyPartyRequestsRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("request_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyPartyRequestsRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `request_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PartyRequestRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyRequestRow>("my_party_requests");
    _table.add_unique_constraint::<u64>("request_id", |row| &row.request_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyRequestRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyRequestRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyRequestRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_party_requestsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyRequestRow`.
    fn my_party_requests(&self) -> __sdk::__query_builder::Table<PartyRequestRow>;
}

impl my_party_requestsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_party_requests(&self) -> __sdk::__query_builder::Table<PartyRequestRow> {
        __sdk::__query_builder::Table::new("my_party_requests")
    }
}
