// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::session_type::Session;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_session`.
///
/// Obtain a handle from the [`MySessionTableAccess::my_session`] method on [`super::RemoteTables`],
/// like `ctx.db.my_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_session().on_insert(...)`.
pub struct MySessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Session>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_session`.
pub struct MySessionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MySessionTableAccessor {
    type Row = Session;
    type Handle<'db> = MySessionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_session()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySessionTableHandle`], which mediates access to the table `my_session`.
    fn my_session(&self) -> MySessionTableHandle<'_>;
}

impl MySessionTableAccess for super::RemoteTables {
    fn my_session(&self) -> MySessionTableHandle<'_> {
        MySessionTableHandle {
            imp: self.imp.get_table::<Session>("my_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySessionInsertCallbackId(__sdk::CallbackId);
pub struct MySessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MySessionTableHandle<'ctx> {
    type Row = Session;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Session> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MySessionTableHandle<'ctx> {
    type Row = Session;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Session> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySessionInsertCallbackId {
        MySessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySessionDeleteCallbackId {
        MySessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MySessionTableHandle<'ctx> {
    type InsertCallbackId = MySessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySessionInsertCallbackId {
        MySessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MySessionTableHandle<'ctx> {
    type DeleteCallbackId = MySessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySessionDeleteCallbackId {
        MySessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MySessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MySessionTableHandle<'ctx> {
    type UpdateCallbackId = MySessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MySessionUpdateCallbackId {
        MySessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MySessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MySessionTableHandle<'ctx> {
    type UpdateCallbackId = MySessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MySessionUpdateCallbackId {
        MySessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MySessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `my_session`,
/// which allows point queries on the field of the same name
/// via the [`MySessionIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_session().identity().find(...)`.
pub struct MySessionIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Session, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MySessionTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `my_session`.
    pub fn identity(&self) -> MySessionIdentityUnique<'ctx> {
        MySessionIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MySessionIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Session> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Session>("my_session");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Session>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Session>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Session`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Session`.
    fn my_session(&self) -> __sdk::__query_builder::Table<Session>;
}

impl my_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_session(&self) -> __sdk::__query_builder::Table<Session> {
        __sdk::__query_builder::Table::new("my_session")
    }
}
