// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub character_id: __sdk::Uuid,
    pub account_id: u64,
    pub normalized_name: String,
    pub display_name: String,
    pub entity_id: u64,
    pub online: bool,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub character_id: __sdk::__query_builder::Col<Player, __sdk::Uuid>,
    pub account_id: __sdk::__query_builder::Col<Player, u64>,
    pub normalized_name: __sdk::__query_builder::Col<Player, String>,
    pub display_name: __sdk::__query_builder::Col<Player, String>,
    pub entity_id: __sdk::__query_builder::Col<Player, u64>,
    pub online: __sdk::__query_builder::Col<Player, bool>,
    pub last_seen: __sdk::__query_builder::Col<Player, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            normalized_name: __sdk::__query_builder::Col::new(table_name, "normalized_name"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub account_id: __sdk::__query_builder::IxCol<Player, u64>,
    pub character_id: __sdk::__query_builder::IxCol<Player, __sdk::Uuid>,
    pub entity_id: __sdk::__query_builder::IxCol<Player, u64>,
    pub normalized_name: __sdk::__query_builder::IxCol<Player, String>,
    pub online: __sdk::__query_builder::IxCol<Player, bool>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            normalized_name: __sdk::__query_builder::IxCol::new(table_name, "normalized_name"),
            online: __sdk::__query_builder::IxCol::new(table_name, "online"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
