// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::boss_phase_row_type::BossPhaseRow;
use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BossState {
    pub entity_id: u64,
    pub kind_id: String,
    pub phase: BossPhaseRow,
    pub arena_center: Vec3Row,
    pub arena_radius: f32,
    pub is_engaged: bool,
    pub engaged_seconds: f32,
    pub rotation_cursor: u32,
}

impl __sdk::InModule for BossState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BossState`.
///
/// Provides typed access to columns for query building.
pub struct BossStateCols {
    pub entity_id: __sdk::__query_builder::Col<BossState, u64>,
    pub kind_id: __sdk::__query_builder::Col<BossState, String>,
    pub phase: __sdk::__query_builder::Col<BossState, BossPhaseRow>,
    pub arena_center: __sdk::__query_builder::Col<BossState, Vec3Row>,
    pub arena_radius: __sdk::__query_builder::Col<BossState, f32>,
    pub is_engaged: __sdk::__query_builder::Col<BossState, bool>,
    pub engaged_seconds: __sdk::__query_builder::Col<BossState, f32>,
    pub rotation_cursor: __sdk::__query_builder::Col<BossState, u32>,
}

impl __sdk::__query_builder::HasCols for BossState {
    type Cols = BossStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BossStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            kind_id: __sdk::__query_builder::Col::new(table_name, "kind_id"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            arena_center: __sdk::__query_builder::Col::new(table_name, "arena_center"),
            arena_radius: __sdk::__query_builder::Col::new(table_name, "arena_radius"),
            is_engaged: __sdk::__query_builder::Col::new(table_name, "is_engaged"),
            engaged_seconds: __sdk::__query_builder::Col::new(table_name, "engaged_seconds"),
            rotation_cursor: __sdk::__query_builder::Col::new(table_name, "rotation_cursor"),
        }
    }
}

/// Indexed column accessor struct for the table `BossState`.
///
/// Provides typed access to indexed columns for query building.
pub struct BossStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<BossState, u64>,
}

impl __sdk::__query_builder::HasIxCols for BossState {
    type IxCols = BossStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BossStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BossState {}
