// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::domain_event_kind_type::DomainEventKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DomainEvent {
    pub id: u64,
    pub occurred_at: __sdk::Timestamp,
    pub kind: DomainEventKind,
    pub actor_entity_id: Option<u64>,
    pub target_entity_id: Option<u64>,
    pub amount: Option<f32>,
    pub source_id: Option<String>,
    pub killer_entity_id: Option<u64>,
    pub payload: Option<String>,
}

impl __sdk::InModule for DomainEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DomainEvent`.
///
/// Provides typed access to columns for query building.
pub struct DomainEventCols {
    pub id: __sdk::__query_builder::Col<DomainEvent, u64>,
    pub occurred_at: __sdk::__query_builder::Col<DomainEvent, __sdk::Timestamp>,
    pub kind: __sdk::__query_builder::Col<DomainEvent, DomainEventKind>,
    pub actor_entity_id: __sdk::__query_builder::Col<DomainEvent, Option<u64>>,
    pub target_entity_id: __sdk::__query_builder::Col<DomainEvent, Option<u64>>,
    pub amount: __sdk::__query_builder::Col<DomainEvent, Option<f32>>,
    pub source_id: __sdk::__query_builder::Col<DomainEvent, Option<String>>,
    pub killer_entity_id: __sdk::__query_builder::Col<DomainEvent, Option<u64>>,
    pub payload: __sdk::__query_builder::Col<DomainEvent, Option<String>>,
}

impl __sdk::__query_builder::HasCols for DomainEvent {
    type Cols = DomainEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DomainEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            occurred_at: __sdk::__query_builder::Col::new(table_name, "occurred_at"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            actor_entity_id: __sdk::__query_builder::Col::new(table_name, "actor_entity_id"),
            target_entity_id: __sdk::__query_builder::Col::new(table_name, "target_entity_id"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            killer_entity_id: __sdk::__query_builder::Col::new(table_name, "killer_entity_id"),
            payload: __sdk::__query_builder::Col::new(table_name, "payload"),
        }
    }
}

/// Indexed column accessor struct for the table `DomainEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct DomainEventIxCols {
    pub id: __sdk::__query_builder::IxCol<DomainEvent, u64>,
    pub occurred_at: __sdk::__query_builder::IxCol<DomainEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for DomainEvent {
    type IxCols = DomainEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DomainEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            occurred_at: __sdk::__query_builder::IxCol::new(table_name, "occurred_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DomainEvent {}
