// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DomainEventConfig {
    pub id: u8,
    pub enabled: bool,
    pub damage_threshold: f32,
    pub retention_seconds: u64,
}

impl __sdk::InModule for DomainEventConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DomainEventConfig`.
///
/// Provides typed access to columns for query building.
pub struct DomainEventConfigCols {
    pub id: __sdk::__query_builder::Col<DomainEventConfig, u8>,
    pub enabled: __sdk::__query_builder::Col<DomainEventConfig, bool>,
    pub damage_threshold: __sdk::__query_builder::Col<DomainEventConfig, f32>,
    pub retention_seconds: __sdk::__query_builder::Col<DomainEventConfig, u64>,
}

impl __sdk::__query_builder::HasCols for DomainEventConfig {
    type Cols = DomainEventConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DomainEventConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
            damage_threshold: __sdk::__query_builder::Col::new(table_name, "damage_threshold"),
            retention_seconds: __sdk::__query_builder::Col::new(table_name, "retention_seconds"),
        }
    }
}

/// Indexed column accessor struct for the table `DomainEventConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct DomainEventConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<DomainEventConfig, u8>,
}

impl __sdk::__query_builder::HasIxCols for DomainEventConfig {
    type IxCols = DomainEventConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DomainEventConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DomainEventConfig {}
