// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::stats_row_type::StatsRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityStats {
    pub entity_id: u64,
    pub stats: StatsRow,
    pub current_mana: f32,
    pub shield_remaining_seconds: Option<f32>,
}

impl __sdk::InModule for EntityStats {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityStats`.
///
/// Provides typed access to columns for query building.
pub struct EntityStatsCols {
    pub entity_id: __sdk::__query_builder::Col<EntityStats, u64>,
    pub stats: __sdk::__query_builder::Col<EntityStats, StatsRow>,
    pub current_mana: __sdk::__query_builder::Col<EntityStats, f32>,
    pub shield_remaining_seconds: __sdk::__query_builder::Col<EntityStats, Option<f32>>,
}

impl __sdk::__query_builder::HasCols for EntityStats {
    type Cols = EntityStatsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityStatsCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            stats: __sdk::__query_builder::Col::new(table_name, "stats"),
            current_mana: __sdk::__query_builder::Col::new(table_name, "current_mana"),
            shield_remaining_seconds: __sdk::__query_builder::Col::new(
                table_name,
                "shield_remaining_seconds",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `EntityStats`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityStatsIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityStats, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityStats {
    type IxCols = EntityStatsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityStatsIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityStats {}
