// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_instance_row_type::ItemInstanceRow;
use super::loot_bag_slot_type::LootBagSlot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `loot_bag_slot`.
///
/// Obtain a handle from the [`LootBagSlotTableAccess::loot_bag_slot`] method on [`super::RemoteTables`],
/// like `ctx.db.loot_bag_slot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loot_bag_slot().on_insert(...)`.
pub struct LootBagSlotTableHandle<'ctx> {
    imp: __sdk::TableHandle<LootBagSlot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `loot_bag_slot`.
pub struct LootBagSlotTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LootBagSlotTableAccessor {
    type Row = LootBagSlot;
    type Handle<'db> = LootBagSlotTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.loot_bag_slot()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `loot_bag_slot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LootBagSlotTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LootBagSlotTableHandle`], which mediates access to the table `loot_bag_slot`.
    fn loot_bag_slot(&self) -> LootBagSlotTableHandle<'_>;
}

impl LootBagSlotTableAccess for super::RemoteTables {
    fn loot_bag_slot(&self) -> LootBagSlotTableHandle<'_> {
        LootBagSlotTableHandle {
            imp: self.imp.get_table::<LootBagSlot>("loot_bag_slot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LootBagSlotInsertCallbackId(__sdk::CallbackId);
pub struct LootBagSlotDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LootBagSlotTableHandle<'ctx> {
    type Row = LootBagSlot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LootBagSlot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LootBagSlotTableHandle<'ctx> {
    type Row = LootBagSlot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LootBagSlot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LootBagSlotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagSlotInsertCallbackId {
        LootBagSlotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LootBagSlotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LootBagSlotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagSlotDeleteCallbackId {
        LootBagSlotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LootBagSlotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LootBagSlotTableHandle<'ctx> {
    type InsertCallbackId = LootBagSlotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagSlotInsertCallbackId {
        LootBagSlotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LootBagSlotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LootBagSlotTableHandle<'ctx> {
    type DeleteCallbackId = LootBagSlotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagSlotDeleteCallbackId {
        LootBagSlotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LootBagSlotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LootBagSlotUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LootBagSlotTableHandle<'ctx> {
    type UpdateCallbackId = LootBagSlotUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LootBagSlotUpdateCallbackId {
        LootBagSlotUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LootBagSlotUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for LootBagSlotTableHandle<'ctx> {
    type UpdateCallbackId = LootBagSlotUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LootBagSlotUpdateCallbackId {
        LootBagSlotUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LootBagSlotUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `loot_bag_slot`,
/// which allows point queries on the field of the same name
/// via the [`LootBagSlotIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loot_bag_slot().id().find(...)`.
pub struct LootBagSlotIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LootBagSlot, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LootBagSlotTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `loot_bag_slot`.
    pub fn id(&self) -> LootBagSlotIdUnique<'ctx> {
        LootBagSlotIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LootBagSlotIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LootBagSlot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LootBagSlot>("loot_bag_slot");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LootBagSlot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LootBagSlot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LootBagSlot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait loot_bag_slotQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LootBagSlot`.
    fn loot_bag_slot(&self) -> __sdk::__query_builder::Table<LootBagSlot>;
}

impl loot_bag_slotQueryTableAccess for __sdk::QueryTableAccessor {
    fn loot_bag_slot(&self) -> __sdk::__query_builder::Table<LootBagSlot> {
        __sdk::__query_builder::Table::new("loot_bag_slot")
    }
}
