// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::loot_bag_type::LootBag;
use super::loot_source_row_type::LootSourceRow;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `loot_bag`.
///
/// Obtain a handle from the [`LootBagTableAccess::loot_bag`] method on [`super::RemoteTables`],
/// like `ctx.db.loot_bag()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loot_bag().on_insert(...)`.
pub struct LootBagTableHandle<'ctx> {
    imp: __sdk::TableHandle<LootBag>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `loot_bag`.
pub struct LootBagTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LootBagTableAccessor {
    type Row = LootBag;
    type Handle<'db> = LootBagTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.loot_bag()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `loot_bag`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LootBagTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LootBagTableHandle`], which mediates access to the table `loot_bag`.
    fn loot_bag(&self) -> LootBagTableHandle<'_>;
}

impl LootBagTableAccess for super::RemoteTables {
    fn loot_bag(&self) -> LootBagTableHandle<'_> {
        LootBagTableHandle {
            imp: self.imp.get_table::<LootBag>("loot_bag"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LootBagInsertCallbackId(__sdk::CallbackId);
pub struct LootBagDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LootBagTableHandle<'ctx> {
    type Row = LootBag;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LootBag> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LootBagTableHandle<'ctx> {
    type Row = LootBag;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LootBag> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LootBagInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagInsertCallbackId {
        LootBagInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LootBagInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LootBagDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagDeleteCallbackId {
        LootBagDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LootBagDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LootBagTableHandle<'ctx> {
    type InsertCallbackId = LootBagInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagInsertCallbackId {
        LootBagInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LootBagInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LootBagTableHandle<'ctx> {
    type DeleteCallbackId = LootBagDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootBagDeleteCallbackId {
        LootBagDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LootBagDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LootBagUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LootBagTableHandle<'ctx> {
    type UpdateCallbackId = LootBagUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LootBagUpdateCallbackId {
        LootBagUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LootBagUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for LootBagTableHandle<'ctx> {
    type UpdateCallbackId = LootBagUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LootBagUpdateCallbackId {
        LootBagUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LootBagUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `loot_bag`,
/// which allows point queries on the field of the same name
/// via the [`LootBagIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loot_bag().id().find(...)`.
pub struct LootBagIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LootBag, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LootBagTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `loot_bag`.
    pub fn id(&self) -> LootBagIdUnique<'ctx> {
        LootBagIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LootBagIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LootBag> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LootBag>("loot_bag");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LootBag>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LootBag>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LootBag`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait loot_bagQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LootBag`.
    fn loot_bag(&self) -> __sdk::__query_builder::Table<LootBag>;
}

impl loot_bagQueryTableAccess for __sdk::QueryTableAccessor {
    fn loot_bag(&self) -> __sdk::__query_builder::Table<LootBag> {
        __sdk::__query_builder::Table::new("loot_bag")
    }
}
