// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LootTakeArgs {
    pub bag_id: u64,
    pub slot_index: u8,
}

impl From<LootTakeArgs> for super::Reducer {
    fn from(args: LootTakeArgs) -> Self {
        Self::LootTake {
            bag_id: args.bag_id,
            slot_index: args.slot_index,
        }
    }
}

impl __sdk::InModule for LootTakeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `loot_take`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait loot_take {
    /// Request that the remote module invoke the reducer `loot_take` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`loot_take:loot_take_then`] to run a callback after the reducer completes.
    fn loot_take(&self, bag_id: u64, slot_index: u8) -> __sdk::Result<()> {
        self.loot_take_then(bag_id, slot_index, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `loot_take` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn loot_take_then(
        &self,
        bag_id: u64,
        slot_index: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl loot_take for super::RemoteReducers {
    fn loot_take_then(
        &self,
        bag_id: u64,
        slot_index: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LootTakeArgs { bag_id, slot_index }, callback)
    }
}
