// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::known_ancient_language_table_type::KnownAncientLanguageTable;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ancient_language`.
///
/// Obtain a handle from the [`MyAncientLanguageTableAccess::my_ancient_language`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ancient_language()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ancient_language().on_insert(...)`.
pub struct MyAncientLanguageTableHandle<'ctx> {
    imp: __sdk::TableHandle<KnownAncientLanguageTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_ancient_language`.
pub struct MyAncientLanguageTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyAncientLanguageTableAccessor {
    type Row = KnownAncientLanguageTable;
    type Handle<'db> = MyAncientLanguageTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_ancient_language()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ancient_language`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyAncientLanguageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyAncientLanguageTableHandle`], which mediates access to the table `my_ancient_language`.
    fn my_ancient_language(&self) -> MyAncientLanguageTableHandle<'_>;
}

impl MyAncientLanguageTableAccess for super::RemoteTables {
    fn my_ancient_language(&self) -> MyAncientLanguageTableHandle<'_> {
        MyAncientLanguageTableHandle {
            imp: self
                .imp
                .get_table::<KnownAncientLanguageTable>("my_ancient_language"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyAncientLanguageInsertCallbackId(__sdk::CallbackId);
pub struct MyAncientLanguageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyAncientLanguageTableHandle<'ctx> {
    type Row = KnownAncientLanguageTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownAncientLanguageTable> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyAncientLanguageTableHandle<'ctx> {
    type Row = KnownAncientLanguageTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownAncientLanguageTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyAncientLanguageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAncientLanguageInsertCallbackId {
        MyAncientLanguageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAncientLanguageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyAncientLanguageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAncientLanguageDeleteCallbackId {
        MyAncientLanguageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAncientLanguageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyAncientLanguageTableHandle<'ctx> {
    type InsertCallbackId = MyAncientLanguageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAncientLanguageInsertCallbackId {
        MyAncientLanguageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAncientLanguageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyAncientLanguageTableHandle<'ctx> {
    type DeleteCallbackId = MyAncientLanguageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAncientLanguageDeleteCallbackId {
        MyAncientLanguageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAncientLanguageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyAncientLanguageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyAncientLanguageTableHandle<'ctx> {
    type UpdateCallbackId = MyAncientLanguageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyAncientLanguageUpdateCallbackId {
        MyAncientLanguageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyAncientLanguageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyAncientLanguageTableHandle<'ctx> {
    type UpdateCallbackId = MyAncientLanguageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyAncientLanguageUpdateCallbackId {
        MyAncientLanguageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyAncientLanguageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<KnownAncientLanguageTable>("my_ancient_language");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<KnownAncientLanguageTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<KnownAncientLanguageTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `KnownAncientLanguageTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ancient_languageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `KnownAncientLanguageTable`.
    fn my_ancient_language(&self) -> __sdk::__query_builder::Table<KnownAncientLanguageTable>;
}

impl my_ancient_languageQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ancient_language(&self) -> __sdk::__query_builder::Table<KnownAncientLanguageTable> {
        __sdk::__query_builder::Table::new("my_ancient_language")
    }
}
