// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_economy_type::AccountEconomy;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_account_economy`.
///
/// Obtain a handle from the [`MyAccountEconomyTableAccess::my_account_economy`] method on [`super::RemoteTables`],
/// like `ctx.db.my_account_economy()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_account_economy().on_insert(...)`.
pub struct MyAccountEconomyTableHandle<'ctx> {
    imp: __sdk::TableHandle<AccountEconomy>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_account_economy`.
pub struct MyAccountEconomyTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyAccountEconomyTableAccessor {
    type Row = AccountEconomy;
    type Handle<'db> = MyAccountEconomyTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_account_economy()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_account_economy`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyAccountEconomyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyAccountEconomyTableHandle`], which mediates access to the table `my_account_economy`.
    fn my_account_economy(&self) -> MyAccountEconomyTableHandle<'_>;
}

impl MyAccountEconomyTableAccess for super::RemoteTables {
    fn my_account_economy(&self) -> MyAccountEconomyTableHandle<'_> {
        MyAccountEconomyTableHandle {
            imp: self.imp.get_table::<AccountEconomy>("my_account_economy"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyAccountEconomyInsertCallbackId(__sdk::CallbackId);
pub struct MyAccountEconomyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyAccountEconomyTableHandle<'ctx> {
    type Row = AccountEconomy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountEconomy> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyAccountEconomyTableHandle<'ctx> {
    type Row = AccountEconomy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountEconomy> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyAccountEconomyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountEconomyInsertCallbackId {
        MyAccountEconomyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAccountEconomyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyAccountEconomyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountEconomyDeleteCallbackId {
        MyAccountEconomyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAccountEconomyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyAccountEconomyTableHandle<'ctx> {
    type InsertCallbackId = MyAccountEconomyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountEconomyInsertCallbackId {
        MyAccountEconomyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAccountEconomyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyAccountEconomyTableHandle<'ctx> {
    type DeleteCallbackId = MyAccountEconomyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountEconomyDeleteCallbackId {
        MyAccountEconomyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAccountEconomyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyAccountEconomyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyAccountEconomyTableHandle<'ctx> {
    type UpdateCallbackId = MyAccountEconomyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyAccountEconomyUpdateCallbackId {
        MyAccountEconomyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyAccountEconomyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyAccountEconomyTableHandle<'ctx> {
    type UpdateCallbackId = MyAccountEconomyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyAccountEconomyUpdateCallbackId {
        MyAccountEconomyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyAccountEconomyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `account_id` unique index on the table `my_account_economy`,
/// which allows point queries on the field of the same name
/// via the [`MyAccountEconomyAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_account_economy().account_id().find(...)`.
pub struct MyAccountEconomyAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AccountEconomy, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyAccountEconomyTableHandle<'ctx> {
    /// Get a handle on the `account_id` unique index on the table `my_account_economy`.
    pub fn account_id(&self) -> MyAccountEconomyAccountIdUnique<'ctx> {
        MyAccountEconomyAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("account_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyAccountEconomyAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `account_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AccountEconomy> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AccountEconomy>("my_account_economy");
    _table.add_unique_constraint::<u64>("account_id", |row| &row.account_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AccountEconomy>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AccountEconomy>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AccountEconomy`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_account_economyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AccountEconomy`.
    fn my_account_economy(&self) -> __sdk::__query_builder::Table<AccountEconomy>;
}

impl my_account_economyQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_account_economy(&self) -> __sdk::__query_builder::Table<AccountEconomy> {
        __sdk::__query_builder::Table::new("my_account_economy")
    }
}
