// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hotbar_row_type::HotbarRow;
use super::hotbar_type::Hotbar;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_hotbar`.
///
/// Obtain a handle from the [`MyHotbarTableAccess::my_hotbar`] method on [`super::RemoteTables`],
/// like `ctx.db.my_hotbar()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_hotbar().on_insert(...)`.
pub struct MyHotbarTableHandle<'ctx> {
    imp: __sdk::TableHandle<Hotbar>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_hotbar`.
pub struct MyHotbarTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyHotbarTableAccessor {
    type Row = Hotbar;
    type Handle<'db> = MyHotbarTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_hotbar()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_hotbar`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyHotbarTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyHotbarTableHandle`], which mediates access to the table `my_hotbar`.
    fn my_hotbar(&self) -> MyHotbarTableHandle<'_>;
}

impl MyHotbarTableAccess for super::RemoteTables {
    fn my_hotbar(&self) -> MyHotbarTableHandle<'_> {
        MyHotbarTableHandle {
            imp: self.imp.get_table::<Hotbar>("my_hotbar"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyHotbarInsertCallbackId(__sdk::CallbackId);
pub struct MyHotbarDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyHotbarTableHandle<'ctx> {
    type Row = Hotbar;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Hotbar> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyHotbarTableHandle<'ctx> {
    type Row = Hotbar;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Hotbar> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyHotbarInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHotbarInsertCallbackId {
        MyHotbarInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyHotbarInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyHotbarDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHotbarDeleteCallbackId {
        MyHotbarDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyHotbarDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyHotbarTableHandle<'ctx> {
    type InsertCallbackId = MyHotbarInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHotbarInsertCallbackId {
        MyHotbarInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyHotbarInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyHotbarTableHandle<'ctx> {
    type DeleteCallbackId = MyHotbarDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHotbarDeleteCallbackId {
        MyHotbarDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyHotbarDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyHotbarUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyHotbarTableHandle<'ctx> {
    type UpdateCallbackId = MyHotbarUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyHotbarUpdateCallbackId {
        MyHotbarUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyHotbarUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyHotbarTableHandle<'ctx> {
    type UpdateCallbackId = MyHotbarUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyHotbarUpdateCallbackId {
        MyHotbarUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyHotbarUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Hotbar>("my_hotbar");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Hotbar>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Hotbar>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Hotbar`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_hotbarQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Hotbar`.
    fn my_hotbar(&self) -> __sdk::__query_builder::Table<Hotbar>;
}

impl my_hotbarQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_hotbar(&self) -> __sdk::__query_builder::Table<Hotbar> {
        __sdk::__query_builder::Table::new("my_hotbar")
    }
}
