// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inventory_table_type::InventoryTable;
use super::item_instance_row_type::ItemInstanceRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_inventory`.
///
/// Obtain a handle from the [`MyInventoryTableAccess::my_inventory`] method on [`super::RemoteTables`],
/// like `ctx.db.my_inventory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_inventory().on_insert(...)`.
pub struct MyInventoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<InventoryTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_inventory`.
pub struct MyInventoryTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyInventoryTableAccessor {
    type Row = InventoryTable;
    type Handle<'db> = MyInventoryTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_inventory()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_inventory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyInventoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyInventoryTableHandle`], which mediates access to the table `my_inventory`.
    fn my_inventory(&self) -> MyInventoryTableHandle<'_>;
}

impl MyInventoryTableAccess for super::RemoteTables {
    fn my_inventory(&self) -> MyInventoryTableHandle<'_> {
        MyInventoryTableHandle {
            imp: self.imp.get_table::<InventoryTable>("my_inventory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyInventoryInsertCallbackId(__sdk::CallbackId);
pub struct MyInventoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyInventoryTableHandle<'ctx> {
    type Row = InventoryTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InventoryTable> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyInventoryTableHandle<'ctx> {
    type Row = InventoryTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InventoryTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyInventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyInventoryInsertCallbackId {
        MyInventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyInventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyInventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyInventoryDeleteCallbackId {
        MyInventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyInventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyInventoryTableHandle<'ctx> {
    type InsertCallbackId = MyInventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyInventoryInsertCallbackId {
        MyInventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyInventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyInventoryTableHandle<'ctx> {
    type DeleteCallbackId = MyInventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyInventoryDeleteCallbackId {
        MyInventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyInventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyInventoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyInventoryTableHandle<'ctx> {
    type UpdateCallbackId = MyInventoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyInventoryUpdateCallbackId {
        MyInventoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyInventoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyInventoryTableHandle<'ctx> {
    type UpdateCallbackId = MyInventoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyInventoryUpdateCallbackId {
        MyInventoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyInventoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InventoryTable>("my_inventory");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InventoryTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InventoryTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InventoryTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_inventoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InventoryTable`.
    fn my_inventory(&self) -> __sdk::__query_builder::Table<InventoryTable>;
}

impl my_inventoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_inventory(&self) -> __sdk::__query_builder::Table<InventoryTable> {
        __sdk::__query_builder::Table::new("my_inventory")
    }
}
