// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resonance_type::Resonance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_resonance`.
///
/// Obtain a handle from the [`MyResonanceTableAccess::my_resonance`] method on [`super::RemoteTables`],
/// like `ctx.db.my_resonance()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_resonance().on_insert(...)`.
pub struct MyResonanceTableHandle<'ctx> {
    imp: __sdk::TableHandle<Resonance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_resonance`.
pub struct MyResonanceTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyResonanceTableAccessor {
    type Row = Resonance;
    type Handle<'db> = MyResonanceTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_resonance()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_resonance`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyResonanceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyResonanceTableHandle`], which mediates access to the table `my_resonance`.
    fn my_resonance(&self) -> MyResonanceTableHandle<'_>;
}

impl MyResonanceTableAccess for super::RemoteTables {
    fn my_resonance(&self) -> MyResonanceTableHandle<'_> {
        MyResonanceTableHandle {
            imp: self.imp.get_table::<Resonance>("my_resonance"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyResonanceInsertCallbackId(__sdk::CallbackId);
pub struct MyResonanceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyResonanceTableHandle<'ctx> {
    type Row = Resonance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Resonance> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyResonanceTableHandle<'ctx> {
    type Row = Resonance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Resonance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyResonanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyResonanceInsertCallbackId {
        MyResonanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyResonanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyResonanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyResonanceDeleteCallbackId {
        MyResonanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyResonanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyResonanceTableHandle<'ctx> {
    type InsertCallbackId = MyResonanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyResonanceInsertCallbackId {
        MyResonanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyResonanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyResonanceTableHandle<'ctx> {
    type DeleteCallbackId = MyResonanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyResonanceDeleteCallbackId {
        MyResonanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyResonanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyResonanceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyResonanceTableHandle<'ctx> {
    type UpdateCallbackId = MyResonanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyResonanceUpdateCallbackId {
        MyResonanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyResonanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyResonanceTableHandle<'ctx> {
    type UpdateCallbackId = MyResonanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyResonanceUpdateCallbackId {
        MyResonanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyResonanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `my_resonance`,
/// which allows point queries on the field of the same name
/// via the [`MyResonanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_resonance().id().find(...)`.
pub struct MyResonanceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Resonance, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyResonanceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `my_resonance`.
    pub fn id(&self) -> MyResonanceIdUnique<'ctx> {
        MyResonanceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyResonanceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Resonance> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Resonance>("my_resonance");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Resonance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Resonance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Resonance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_resonanceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Resonance`.
    fn my_resonance(&self) -> __sdk::__query_builder::Table<Resonance>;
}

impl my_resonanceQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_resonance(&self) -> __sdk::__query_builder::Table<Resonance> {
        __sdk::__query_builder::Table::new("my_resonance")
    }
}
