// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_wallet_type::CharacterWallet;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_wallet`.
///
/// Obtain a handle from the [`MyWalletTableAccess::my_wallet`] method on [`super::RemoteTables`],
/// like `ctx.db.my_wallet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_wallet().on_insert(...)`.
pub struct MyWalletTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterWallet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_wallet`.
pub struct MyWalletTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyWalletTableAccessor {
    type Row = CharacterWallet;
    type Handle<'db> = MyWalletTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_wallet()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_wallet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyWalletTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyWalletTableHandle`], which mediates access to the table `my_wallet`.
    fn my_wallet(&self) -> MyWalletTableHandle<'_>;
}

impl MyWalletTableAccess for super::RemoteTables {
    fn my_wallet(&self) -> MyWalletTableHandle<'_> {
        MyWalletTableHandle {
            imp: self.imp.get_table::<CharacterWallet>("my_wallet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyWalletInsertCallbackId(__sdk::CallbackId);
pub struct MyWalletDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyWalletTableHandle<'ctx> {
    type Row = CharacterWallet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterWallet> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyWalletTableHandle<'ctx> {
    type Row = CharacterWallet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterWallet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyWalletInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyWalletInsertCallbackId {
        MyWalletInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyWalletInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyWalletDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyWalletDeleteCallbackId {
        MyWalletDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyWalletDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyWalletTableHandle<'ctx> {
    type InsertCallbackId = MyWalletInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyWalletInsertCallbackId {
        MyWalletInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyWalletInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyWalletTableHandle<'ctx> {
    type DeleteCallbackId = MyWalletDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyWalletDeleteCallbackId {
        MyWalletDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyWalletDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyWalletUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyWalletTableHandle<'ctx> {
    type UpdateCallbackId = MyWalletUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyWalletUpdateCallbackId {
        MyWalletUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyWalletUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyWalletTableHandle<'ctx> {
    type UpdateCallbackId = MyWalletUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyWalletUpdateCallbackId {
        MyWalletUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyWalletUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterWallet>("my_wallet");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterWallet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterWallet>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterWallet`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_walletQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterWallet`.
    fn my_wallet(&self) -> __sdk::__query_builder::Table<CharacterWallet>;
}

impl my_walletQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_wallet(&self) -> __sdk::__query_builder::Table<CharacterWallet> {
        __sdk::__query_builder::Table::new("my_wallet")
    }
}
