// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::party_request_kind_type::PartyRequestKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyRequestRow {
    pub request_id: u64,
    pub party_id: u64,
    pub kind: PartyRequestKind,
    pub initiator: __sdk::Uuid,
    pub recipient: __sdk::Uuid,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for PartyRequestRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyRequestRow`.
///
/// Provides typed access to columns for query building.
pub struct PartyRequestRowCols {
    pub request_id: __sdk::__query_builder::Col<PartyRequestRow, u64>,
    pub party_id: __sdk::__query_builder::Col<PartyRequestRow, u64>,
    pub kind: __sdk::__query_builder::Col<PartyRequestRow, PartyRequestKind>,
    pub initiator: __sdk::__query_builder::Col<PartyRequestRow, __sdk::Uuid>,
    pub recipient: __sdk::__query_builder::Col<PartyRequestRow, __sdk::Uuid>,
    pub created_at: __sdk::__query_builder::Col<PartyRequestRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PartyRequestRow {
    type Cols = PartyRequestRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyRequestRowCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            initiator: __sdk::__query_builder::Col::new(table_name, "initiator"),
            recipient: __sdk::__query_builder::Col::new(table_name, "recipient"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyRequestRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyRequestRowIxCols {
    pub initiator: __sdk::__query_builder::IxCol<PartyRequestRow, __sdk::Uuid>,
    pub recipient: __sdk::__query_builder::IxCol<PartyRequestRow, __sdk::Uuid>,
    pub request_id: __sdk::__query_builder::IxCol<PartyRequestRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for PartyRequestRow {
    type IxCols = PartyRequestRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyRequestRowIxCols {
            initiator: __sdk::__query_builder::IxCol::new(table_name, "initiator"),
            recipient: __sdk::__query_builder::IxCol::new(table_name, "recipient"),
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyRequestRow {}
