// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Resonance {
    pub id: u64,
    pub character_id: __sdk::Uuid,
    pub root_word_id: String,
    pub xp: u64,
    pub level: u32,
}

impl __sdk::InModule for Resonance {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Resonance`.
///
/// Provides typed access to columns for query building.
pub struct ResonanceCols {
    pub id: __sdk::__query_builder::Col<Resonance, u64>,
    pub character_id: __sdk::__query_builder::Col<Resonance, __sdk::Uuid>,
    pub root_word_id: __sdk::__query_builder::Col<Resonance, String>,
    pub xp: __sdk::__query_builder::Col<Resonance, u64>,
    pub level: __sdk::__query_builder::Col<Resonance, u32>,
}

impl __sdk::__query_builder::HasCols for Resonance {
    type Cols = ResonanceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResonanceCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            root_word_id: __sdk::__query_builder::Col::new(table_name, "root_word_id"),
            xp: __sdk::__query_builder::Col::new(table_name, "xp"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
        }
    }
}

/// Indexed column accessor struct for the table `Resonance`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResonanceIxCols {
    pub character_id: __sdk::__query_builder::IxCol<Resonance, __sdk::Uuid>,
    pub id: __sdk::__query_builder::IxCol<Resonance, u64>,
}

impl __sdk::__query_builder::HasIxCols for Resonance {
    type IxCols = ResonanceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResonanceIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Resonance {}
