// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StatsRow {
    pub current_health: f32,
    pub max_health: f32,
    pub current_shield: f32,
    pub max_shield: f32,
    pub max_mana: f32,
    pub mana_regeneration: f32,
    pub armor: f32,
    pub movement_speed: f32,
    pub attack_power: f32,
    pub threat_generation: f32,
    pub gathering_speed: f32,
    pub gathering_bonus: f32,
}

impl __sdk::InModule for StatsRow {
    type Module = super::RemoteModule;
}
